import {accountStorage} from './account-storage.mjs';
let user=null,registerMode=false,googleConfigured=false;
const $=s=>document.querySelector(s);
export function getAccount(){return user;}
async function api(action,data){const response=await fetch('/api/account/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Object.assign(Error(result.error||'Connexion impossible.'),{code:result.code});return result;}
function showAuth(){document.body.classList.remove('authenticated');$('#authScreen').hidden=false;}
function drawUser(){$('#accountEmailStatus').textContent=user.emailVerified?'Adresse e-mail vérifiée.':'Adresse e-mail non vérifiée.';$('#verifyAccountEmail').hidden=user.emailVerified;$('#accountMethods').textContent=user.googleLinked?(user.hasPassword?'E-mail / mot de passe et Google associés.':'Connexion avec Google.'):'Connexion par e-mail et mot de passe.';$('#googleLinkFields').hidden=user.googleLinked;$('#googleLink').disabled=!googleConfigured;$('#googleLinkPassword').value='';$('#accountButton').textContent=user.name||user.email;$('#accountLoginEmail').value=user.email;$('#accountName').value=user.name;$('#accountTaskrabbitEmail').value=user.taskrabbitEmail||'';$('#email').value=user.taskrabbitEmail||'';}
async function startApp(){await accountStorage.initialize();
 // Remove matching legacy copies only after the migrated account data has loaded successfully.
 const legacyKeys=['taskpilot-v1','taskpilot-requests','taskpilot-alerts'].filter(key=>localStorage.getItem(key)!==null);
 if(legacyKeys.length&&legacyKeys.every(key=>localStorage.getItem(key)===accountStorage.getItem(key))){for(const key of legacyKeys)localStorage.removeItem(key);localStorage.setItem('taskpilot-migration-owner',user.id);}
 drawUser();await import('./app.mjs');document.body.classList.add('authenticated');$('#authScreen').hidden=true;if(!user.taskrabbitSetupDone&&!user.taskrabbitEmail&&!$('#emailTokenDialog').open){$('#welcomeTaskrabbitEmail').value='';$('#welcomeTaskrabbitError').textContent='';$('#taskrabbitWelcome').showModal();}}
function mode(register){registerMode=register;$('#authTitle').textContent=register?'Créer votre compte':'Se connecter';$('#authSubmit').textContent=register?'Créer mon compte':'Se connecter';$('#authTabLogin').classList.toggle('active',!register);$('#authTabRegister').classList.toggle('active',register);$('#registrationFields').hidden=!register;$('#registrationFields').querySelectorAll('input').forEach(input=>input.disabled=!register);$('#loginPassword').minLength=register?10:1;$('#loginPassword').autocomplete=register?'new-password':'current-password';$('#authError').textContent='';}
$('#authTabLogin').onclick=()=>mode(false);$('#authTabRegister').onclick=()=>mode(true);
const legacyPresent=!!localStorage.getItem('taskpilot-v1')&&!localStorage.getItem('taskpilot-migration-owner');$('#migrationChoice').hidden=!legacyPresent;$('#migrateExisting').checked=legacyPresent;
$('#authForm').onsubmit=async e=>{e.preventDefault();const button=$('#authSubmit');button.disabled=true;$('#authError').textContent='';try{const data={email:$('#loginEmail').value,password:$('#loginPassword').value};if(registerMode){if(data.password!==$('#registerPasswordConfirm').value)throw Error('Les deux mots de passe doivent être identiques.');data.name=$('#registerName').value;data.taskrabbitEmail=$('#registerTaskrabbitEmail').value;if(legacyPresent&&$('#migrateExisting').checked){data.state={};for(const key of ['taskpilot-v1','taskpilot-requests','taskpilot-alerts']){const value=localStorage.getItem(key);if(value!==null)data.state[key]=value;}}}const result=await api(registerMode?'register':'login',data);if(result.requiresVerification){$('#authError').textContent=result.message;mode(false);$('#authError').textContent=result.message;$('#loginPassword').value='';return;}user=result.user;if(registerMode&&data.state)localStorage.setItem('taskpilot-migration-owner',user.id);$('#authForm').reset();await startApp();}catch(e){$('#authError').textContent=e.message;}finally{button.disabled=false;}};
$('#accountButton').onclick=()=>{drawUser();$('#profileError').textContent='';$('#accountDialog').showModal();};
$('#accountForm').onsubmit=async e=>{e.preventDefault();$('#profileError').textContent='';const button=$('#saveProfile');button.disabled=true;try{const result=await api('profile',{name:$('#accountName').value,taskrabbitEmail:$('#accountTaskrabbitEmail').value});user=result.user;drawUser();$('#profileError').textContent='Profil enregistré.';}catch(e){$('#profileError').textContent=e.message;}finally{button.disabled=false;}};
$('#logout').onclick=async()=>{try{await accountStorage.flush();await api('logout',{});location.reload();}catch(e){$('#profileError').textContent=e.message;}};
$('#savePortalEmail').onclick=async()=>{if(!$('#email').reportValidity())return;try{const result=await api('profile',{taskrabbitEmail:$('#email').value});user=result.user;drawUser();$('#portalEmailStatus').textContent='Adresse Taskrabbit enregistrée dans votre profil.';}catch(e){$('#portalEmailStatus').textContent=e.message;}};
let savingWelcome=false;
async function finishTaskrabbitWelcome(skip=false){if(savingWelcome)return;savingWelcome=true;$('#welcomeTaskrabbitError').textContent='';$('#saveTaskrabbitWelcome').disabled=true;$('#skipTaskrabbitWelcome').disabled=true;try{const data=skip?{taskrabbitSetupDone:true}:{taskrabbitEmail:$('#welcomeTaskrabbitEmail').value,taskrabbitSetupDone:true};const result=await api('profile',data);user=result.user;drawUser();$('#taskrabbitWelcome').close();}catch(e){$('#welcomeTaskrabbitError').textContent=e.message;}finally{savingWelcome=false;$('#saveTaskrabbitWelcome').disabled=false;$('#skipTaskrabbitWelcome').disabled=false;}}
$('#taskrabbitWelcomeForm').onsubmit=e=>{e.preventDefault();finishTaskrabbitWelcome();};
$('#skipTaskrabbitWelcome').onclick=()=>finishTaskrabbitWelcome(true);
$('#useLoginEmail').onclick=()=>{$('#welcomeTaskrabbitEmail').value=user.email;$('#welcomeTaskrabbitEmail').focus();};
$('#taskrabbitWelcome').addEventListener('cancel',e=>e.preventDefault());
window.addEventListener('beforeunload',e=>{if(accountStorage.hasPending){e.preventDefault();e.returnValue='';}});
mode(false);showAuth();
await (await import('./email-account-client.mjs')).initializeEmailAccount(getAccount);
try{const response=await fetch('/api/account/me');if(!response.ok)throw Error('Serveur local indisponible.');const result=await response.json();user=result.user;if(user)await startApp();}catch(e){$('#authError').textContent=e.message;}

const authMessages={google_cancelled:'Connexion Google annulée. Vous pouvez réessayer.',google_existing:'Ce compte existe déjà. Connectez-vous avec votre mot de passe, puis associez Google dans Mon compte.',google_conflict:'Ce compte Google est déjà associé à un autre compte TaskPilot.',google_failed:'Connexion Google impossible ou expirée. Réessayez et vérifiez la configuration Google.'};
const params=new URLSearchParams(location.search),authError=params.get('authError');if(authError){$('#authError').textContent=authMessages[authError]||'Connexion impossible.';history.replaceState(null,'',location.pathname);}
async function continueGoogle(link=false){const button=$(link?'#googleLink':'#googleLogin'),message=$(link?'#profileError':'#authError');button.disabled=true;message.textContent='';try{
 const data=link?{link:true,password:$('#googleLinkPassword').value}:{};
 if(!link&&registerMode){data.taskrabbitEmail=$('#registerTaskrabbitEmail').value;if(legacyPresent&&$('#migrateExisting').checked){data.state={};for(const key of ['taskpilot-v1','taskpilot-requests','taskpilot-alerts']){const value=localStorage.getItem(key);if(value!==null)data.state[key]=value;}}}
 if(link&&!data.password)throw Error('Renseignez votre mot de passe pour associer Google.');
 await accountStorage.flush();const result=await api('google/start',data);location.assign(result.url);
 }catch(e){message.textContent=e.message;button.disabled=!googleConfigured;}}
$('#googleLogin').onclick=()=>continueGoogle();$('#googleLink').onclick=()=>continueGoogle(true);
try{const response=await fetch('/api/account/google/config');if(!response.ok)throw Error();googleConfigured=(await response.json()).configured;$('#googleSetupLink').hidden=googleConfigured;$('#googleLogin').disabled=!googleConfigured;$('#googleLink').disabled=!googleConfigured;$('#googleAvailability').textContent=googleConfigured?'Google utilise votre e-mail et votre profil pour vous connecter.':'Google sera disponible après configuration par le propriétaire de TaskPilot.';}catch{$('#googleLogin').disabled=true;$('#googleLink').disabled=true;$('#googleAvailability').textContent='Impossible de vérifier la disponibilité de Google.';}
