import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,rm,rmdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {Readable} from 'node:stream';
import {randomBytes} from 'node:crypto';
import {createAccountService} from './account-server.mjs';
import {createProtectedStorage} from './protected-storage.mjs';
const work=fileURLToPath(new URL('../../work/',import.meta.url));await mkdir(work,{recursive:true});const folder=await mkdtemp(path.join(work,'account-tests-')),file=path.join(folder,'accounts.json');
const storage=await createProtectedStorage(file,{key:randomBytes(32)});
const service=await createAccountService(file,{storage,googleConfig:{}}),password=randomBytes(18).toString('base64');let cookieA,cookieB;
async function request(action,{method='GET',data={},cookie='',origin='http://127.0.0.1:4173'}={}){const req=Readable.from([Buffer.from(JSON.stringify(data))]);req.method=method;req.headers={host:'127.0.0.1:4173',origin,'content-type':'application/json',cookie};req.socket={remoteAddress:'127.0.0.1'};let status,headers,payload;await service.api(req,{writeHead(s,h){status=s;headers=h;},end(s){payload=JSON.parse(s);}},new URL('http://127.0.0.1:4173/api/account/'+action));return {status,headers,payload};}
after(async()=>{assert.ok(folder.startsWith(work)&&path.basename(folder).startsWith('account-tests-'));await rm(file,{force:true});await rm(file+'.tmp',{force:true});await rmdir(folder);});
test('Inscription avec deux e-mails distincts et mot de passe haché',async()=>{const r=await request('register',{method:'POST',data:{email:'account-a@example.invalid',taskrabbitEmail:'taskrabbit-a@example.invalid',password}});assert.equal(r.status,200);assert.notEqual(r.payload.user.email,r.payload.user.taskrabbitEmail);assert.ok(!('passwordHash' in r.payload.user));cookieA=r.headers['Set-Cookie'].split(';')[0];assert.match(r.headers['Set-Cookie'],/HttpOnly; SameSite=Strict/);assert.ok(!(await readFile(file,'utf8')).includes(password));});
test('Refus de connexion incorrecte et d’inscription en double',async()=>{assert.equal((await request('login',{method:'POST',data:{email:'account-a@example.invalid',password:'wrong'}})).status,401);assert.equal((await request('register',{method:'POST',data:{email:'account-a@example.invalid',password}})).status,409);});
test('Connexion réussie et session conservée après redémarrage',async()=>{const r=await request('login',{method:'POST',data:{email:'ACCOUNT-A@EXAMPLE.INVALID',password}});assert.equal(r.status,200);const previous=cookieA;cookieA=r.headers['Set-Cookie'].split(';')[0];const restarted=await createAccountService(file,{storage,googleConfig:{}});assert.equal(restarted.authenticated({headers:{cookie:cookieA}}).email,'account-a@example.invalid');assert.ok(restarted.authenticated({headers:{cookie:previous}}));});
test('Profil Taskrabbit modifiable sans changer l’e-mail de connexion',async()=>{const r=await request('profile',{method:'POST',cookie:cookieA,data:{name:'Compte test',taskrabbitEmail:'different-taskrabbit@example.invalid'}});assert.equal(r.status,200);assert.equal(r.payload.user.email,'account-a@example.invalid');assert.equal(r.payload.user.taskrabbitEmail,'different-taskrabbit@example.invalid');});
test('Données isolées entre utilisateurs et protection contre un onglet obsolète',async()=>{const r=await request('register',{method:'POST',data:{email:'account-b@example.invalid',password}});cookieB=r.headers['Set-Cookie'].split(';')[0];assert.equal((await request('state',{method:'PUT',cookie:cookieA,data:{state:{'taskpilot-alerts':'true'},revision:0}})).status,200);assert.deepEqual((await request('state',{cookie:cookieB})).payload.state,{});assert.equal((await request('state',{method:'PUT',cookie:cookieA,data:{state:{},revision:0}})).status,409);assert.equal((await request('state')).status,401);});
test('Origine étrangère refusée et déconnexion invalide la session',async()=>{assert.equal((await request('profile',{method:'POST',cookie:cookieA,origin:'https://foreign.invalid',data:{taskrabbitEmail:'x@example.invalid'}})).status,403);assert.equal((await request('logout',{method:'POST',cookie:cookieA})).status,200);assert.equal((await request('me',{cookie:cookieA})).payload.user,null);});

test('Première connexion : choix Plus tard conservé après redémarrage sans effacer le profil',async()=>{assert.equal((await request('me',{cookie:cookieB})).payload.user.taskrabbitSetupDone,false);const r=await request('profile',{method:'POST',cookie:cookieB,data:{taskrabbitSetupDone:true}});assert.equal(r.status,200);assert.equal(r.payload.user.taskrabbitSetupDone,true);assert.equal(r.payload.user.taskrabbitEmail,'');const restarted=await createAccountService(file,{storage,googleConfig:{}});assert.equal(restarted.authenticated({headers:{cookie:cookieB}}).taskrabbitSetupDone,true);});
test('Adresse Taskrabbit : validation, conservation et indépendance de l’e-mail TaskPilot',async()=>{assert.equal((await request('profile',{method:'POST',cookie:cookieB,data:{taskrabbitEmail:'invalide',taskrabbitSetupDone:true}})).status,400);const r=await request('profile',{method:'POST',cookie:cookieB,data:{taskrabbitEmail:'future-planning@example.invalid'}});assert.equal(r.status,200);assert.equal(r.payload.user.taskrabbitSetupDone,true);assert.equal(r.payload.user.email,'account-b@example.invalid');const renamed=await request('profile',{method:'POST',cookie:cookieB,data:{name:'Nom modifié'}});assert.equal(renamed.payload.user.taskrabbitEmail,'future-planning@example.invalid');const restarted=await createAccountService(file,{storage,googleConfig:{}});assert.equal(restarted.authenticated({headers:{cookie:cookieB}}).taskrabbitEmail,'future-planning@example.invalid');});
