import {weekDays,workingDays,isWorkingDate,workDaysLabel} from './workdays.mjs';
import {accountStorage} from './account-storage.mjs';
import {reservations,reservationDay} from './reservations.mjs';
import {roadMatrix} from './road-routes.mjs';
import {setupRequestQueue} from './request-queue.mjs';
import {setupOffers} from './offers-ui.mjs';
import {mergeOffers,geocodeAddress} from './offers.mjs';
import {routeKey} from './transit-core.mjs';
import {journeyDetails} from './journey-view.mjs';
import {TransportSettings} from './transit-ui.mjs';
import {transportNames} from './transit-core.mjs';
import {ZonePicker} from './zones.mjs';
import {defaults,tomorrow,demo,normalizeTasks,optimize,reasons,hhmm,mins,validatePrefs} from './model.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n),duration=n=>`${Math.floor(n/60)} h ${String(Math.round(n%60)).padStart(2,'0')}`;
const saved=(()=>{try{return JSON.parse(accountStorage.getItem('taskpilot-v1'))||{};}catch{return {};}})();let p={...defaults,...saved.prefs,placeResolved:saved.prefs?Boolean(saved.prefs.placeResolved):true,zoneMode:saved.prefs?.zoneMode||(saved.prefs?(saved.prefs.departments?'departments':'all'):defaults.zoneMode)},date=tomorrow(),tasks=saved.tasks?normalizeTasks(saved.tasks):demo(date),isDemo=saved.isDemo??true,demoCity=saved.demoCity||(saved.tasks?.some(t=>t.department==='Paris')?'paris':'lyon'),matrix=saved.matrix||{},result=null,selected=0,editing=null;
let planningMode=saved.planningMode||'confirmed';
function planningTasks(){return planningMode==='confirmed'?reservationDay(tasks,date).confirmed:tasks;}
function save(){accountStorage.setItem('taskpilot-v1',JSON.stringify({prefs:p,tasks,isDemo,demoCity,matrix,transitMatrix,planningMode}));}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000);}
function view(v){if(v!=='settings'&&!$('#settingsView').hidden&&!synchronizePrefs())return;for(const name of ['plan','missions','settings'])$(`#${name}View`).hidden=name!==v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#heading').textContent={plan:'Organiser demain.',missions:'Trouver les bonnes missions.',settings:'Une journée à votre mesure.'}[v];if(v==='settings')requestAnimationFrame(()=>zonePicker?.fitZone());}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
let zonePicker,transportPicker,transitMatrix=saved.transitMatrix||{},activeTransitJob=null;
const groups=[['01 · Disponibilités', [['start','Début de disponibilité','time'],['end','Fin de disponibilité','time'],['maxTasks','Missions maximum','number',1,12],['maxWork','Travail maximum (heures)','number',.5,24,.5],['blocked','Créneaux indisponibles','text',null,null,null,'Ex. 10:00-11:00,16:00-17:00'],['returnHome','Inclure le retour au point de départ','checkbox']]],['02 · Trajets et zones', [['origin','Nom du point de départ','text'],['lat','Latitude de départ','number',-90,90,.000001],['lon','Longitude de départ','number',-180,180,.000001],['speed','Vitesse moyenne (km/h)','number',1,130],['detour','Coefficient de détour','number',1,3,.05],['maxFirst','Trajet initial maximum (min)','number',0,600],['maxTravel','Trajet entre missions maximum (min)','number',0,600],['maxKm','Distance quotidienne maximum (km)','number',0,2000],['departments','Départements autorisés','text',null,null,null,'Noms séparés par des virgules ; vide = tous'],['excluded','Départements exclus','text',null,null,null,'Noms séparés par des virgules']]],['03 · Marges et pauses', [['gap','Marge entre missions, hors trajet (min)','number',0,180],['overrun','Supplément sur durée du montage (%)','number',0,100],['lunch','Prévoir une pause déjeuner','checkbox'],['lunchStart','Début de la pause déjeuner','time'],['lunchDuration','Durée du déjeuner (min)','number',0,180]]],['04 · Revenus et préférences', [['minPay','Paiement minimum par mission (€)','number',0,5000],['minRate','Revenu horaire après déplacements (€)','number',0,1000],['costKm','Coût du déplacement (€ / km)','number',0,10,.01],['target','Objectif après déplacements (€)','number',0,10000],['brands','Marques acceptées','text',null,null,null,'Ex. IKEA,Homary ; vide = toutes'],['keywords','Meubles préférés','text',null,null,null,'Au moins un mot doit correspondre ; vide = tous'],['avoid','Meubles ou mots à exclure','text',null,null,null,'Ex. dressing,armoire'],['minDuration','Durée estimée minimale (min)','number',0,1440],['maxDuration','Durée estimée maximale (min)','number',1,1440]]],['05 · Gestion des demandes', [['maxPending','Demandes en attente maximum','number',0,12]]]];
function field([name,label,type,min,max,step,hint],value){return `<label class="${type==='checkbox'?'checkbox':''}">${type==='checkbox'?`<input name="${name}" type="checkbox" ${value?'checked':''}>${esc(label)}`:`${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${min!=null?`min="${min}"`:''} ${max!=null?`max="${max}"`:''} ${type==='number'?`step="${step||1}"`:''} ${type==='text'?'':'required'}>`}${hint?`<span class="hint">${esc(hint)}</span>`:''}</label>`;}
groups[1][1]=groups[1][1].filter(f=>!['origin','lat','lon','departments','excluded'].includes(f[0]));
function settings(){ clearTimeout(criteriaTimer);zonePicker?.destroy();$('#settingsFields').innerHTML=groups.map(([title,fields],i)=>`<details ${i===0||i===1?'open':''}><summary>${esc(title)}</summary>${i===0?`<fieldset class="workdays-picker"><legend>Jours travaillés</legend><p class="hint">Cochez les jours où vous souhaitez travailler. Les jours non cochés sont vos jours de repos.</p><div class="workdays-options">${weekDays.map(day=>`<label class="checkbox"><input type="checkbox" name="workDays" value="${day.value}" ${workingDays(p).includes(day.value)?'checked':''}>${day.label}</label>`).join('')}</div><p class="hint">Aucun jour coché = aucune planification.</p></fieldset>`:''}${i===1?'<div id="zonePicker"></div><div id="transportPicker"></div>':''}<div class="field-grid">${fields.map(f=>field(f,p[f[0]])).join('')}</div>${i===1?'<p class="muted">Le rayon délimite la zone ; les temps de trajet restent des limites distinctes. En transports, les horaires du fournisseur remplacent les estimations.</p><button type="button" class="secondary" id="roadRoutes">Calculer les routes voiture / marche avec IGN</button><button type="button" class="secondary" id="editMatrix">Renseigner des trajets vérifiés</button>':''}${i===4?'<p class="muted">Ce plafond inclut les demandes déjà en attente et les nouvelles missions proposées. Il limite les créneaux immobilisés. L’envoi automatique est désactivé.</p>':''}</details>`).join('');zonePicker=new ZonePicker($('#zonePicker'),p,tasks);transportPicker=new TransportSettings($('#transportPicker'),p,{onCalculate:runTransitCalculation,onStatus:mode=>{for(const key of ['speed','detour','maxKm','costKm']){const input=document.querySelector('[name="'+key+'"]');if(input)input.closest('label').hidden=key==='speed'?mode!=='car':key==='costKm'?['transit','walk'].includes(mode):mode==='transit';}$('#editMatrix').hidden=mode==='transit';$('#roadRoutes').hidden=!['car','walk'].includes(mode);}});$('#zonePicker').closest('details').addEventListener('toggle',()=>{if($('#zonePicker').closest('details').open)requestAnimationFrame(()=>zonePicker.fitZone());});$('#roadRoutes').onclick=async()=>{const b=$('#roadRoutes');if(!synchronizePrefs())return;if(!isWorkingDate(date,p)){toast('Jour de repos : aucun trajet à calculer.');return;}b.disabled=true;try{const snapshot=JSON.stringify({p,date,tasks,planningMode});const next=await roadMatrix(planningTasks(),p,date,matrix,(n,total)=>{$('#criteriaStatus').textContent=n+' / '+total+' routes IGN calculées (sans trafic temps réel).';});if(snapshot!==JSON.stringify({p,date,tasks,planningMode}))throw Error('Les critères ont changé. Relancez les routes.');matrix=next;save();calculate();view('plan');toast('Routes IGN calculées. Temps théoriques sans trafic temps réel.');}catch(e){toast(e.message);}finally{b.disabled=!isWorkingDate(date,p);}};$('#editMatrix').onclick=()=>{$('#matrixText').value=JSON.stringify(matrix,null,2);$('#matrixDialog').showModal();};}
function calculate(){try{transitMatrix=Object.fromEntries(Object.entries(transitMatrix).filter(([,v])=>v.fetchedAt>Date.now()-600000));result=!isWorkingDate(date,p)?{plans:[],eligible:0,dayOff:true}:planningMode==='confirmed'&&reservationDay(tasks,date).pending.length?{plans:[],eligible:0,pendingDecision:true}:optimize(planningTasks(),planningMode==='confirmed'?{...p,minRate:0}:p,date,{...matrix,...transitMatrix});selected=0;renderPlan();renderTasks();if(zonePicker){zonePicker.tasks=tasks;zonePicker.draw();}save();}catch(e){result={plans:[],eligible:0};selected=0;renderPlan();renderTasks();toast(e.message);}}
function currentTransit(){const home={id:'home',lat:p.lat,lon:p.lon};return planningTasks().some(t=>t.date===date&&transitMatrix[routeKey(home,t,p,date,{arrivalBy:mins(t.time)-p.transitBuffer})]?.fetchedAt>Date.now()-600000);}
function renderPlan(){renderReservations();const plan=result?.plans[selected],dayOff=!isWorkingDate(date,p);for(const id of ['calculateTransit','roadRoutes']){const button=$('#'+id);if(button)button.disabled=dayOff||!!activeTransitJob;}$('#planningMode').value=planningMode;$('#objective').closest('label').hidden=planningMode==='confirmed';$('#prepareRequests').hidden=planningMode==='confirmed';$('#prepareRequests').disabled=dayOff||!plan;$('#calculate').disabled=dayOff||!!activeTransitJob||(planningMode==='confirmed'&&(reservationDay(tasks,date).pending.length>0||!planningTasks().length));$('#calculate').textContent=planningMode==='confirmed'?'Calculer mes missions confirmées ↗':p.mobility==='transit'?'Calculer avec les horaires ↗':'Calculer mes propositions ↗';$('.notes .estimate').innerHTML=p.mobility==='transit'?'<strong>Horaires des transports</strong><p>Le calcul du planning utilise les lignes et heures de départ du fournisseur. La marche, les correspondances et votre marge d’arrivée sont incluses. Vérifiez les perturbations avant le départ.</p>':'<strong>Trajets estimés</strong><p>Calculés avec votre vitesse et le coefficient de détour, ou à partir de durées renseignées manuellement. Mode : '+esc(transportNames[p.mobility])+'.</p>';$('#sourceLabel').textContent=isDemo?'Données de démonstration':`${tasks.length} missions importées / saisies`;
$('#demoControls').hidden=!isDemo;$('#sourceDetail').textContent=isDemo?'Missions fictives '+(demoCity==='paris'?'à Paris et en Île-de-France':'autour de Lyon')+'. Aucune offre réelle ni demande envoyée.':'Liste locale : actualisez-la depuis le portail. Aucun envoi automatique de demande.';
$('#stats').innerHTML=[['Revenu après déplacements',money(plan?.net||0),`${money(plan?.pay||0)} brut − frais estimés`],['Revenu par heure',`${Math.round(plan?.rate||0)} €/h`,'Trajets, marges et attentes inclus'],[planningMode==='confirmed'?'Missions confirmées planifiées':'Missions proposées',String(plan?.seq.length||0),planningMode==='confirmed'?`${reservationDay(tasks,date).confirmed.length} missions à inclure, sans sélection par rentabilité`:`${result?.eligible||0} respectent les filtres initiaux`],['Temps de trajet',duration(plan?.drive||0),p.mobility==='transit'?'Marche, attentes et correspondances':`${Math.round(plan?.distance||0)} km ${plan?.estimated?'estimés':'renseignés'}`]].map(([l,v,n])=>`<div class="stat"><small>${l}</small><strong>${v}</strong><p>${n}</p></div>`).join('');
$('#rules').innerHTML=[['Point de départ',p.origin],['Zone',p.zoneMode==='radius'?p.radiusKm+' km autour du point de départ':p.zoneMode==='departments'?p.departments||'Aucun département':'France entière'],['Déplacement',transportNames[p.mobility]],['Jours travaillés',workDaysLabel(p)],['Disponibilité',`${p.start} – ${p.end}`],['Marge hors trajet',`${p.gap} min`],['Prudence sur le montage',`+ ${p.overrun} %`],['Pause déjeuner',p.lunch?`${p.lunchStart} · ${p.lunchDuration} min`:'Sans pause fixe'],['Trajet entre missions',`${p.maxTravel} min max.`],['Plafond de demandes',`${p.maxPending}`]].map(([a,b])=>`<div class="rule"><span>${a}</span><strong>${b}</strong></div>`).join('');
$('#alternatives').innerHTML=plan&&planningMode==='proposals'?`<div class="alternatives">${result.plans.map((x,i)=>`<button class="alternative ${i===selected?'selected':''}" data-alt="${i}">Option ${i+1} · ${money(x.net)} · ${Math.round(x.rate)} €/h</button>`).join('')}</div>`:'';document.querySelectorAll('[data-alt]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.alt);renderPlan();});
$('#ics').disabled=!plan;
if(dayOff){$('#timeline').innerHTML='<div class="empty day-off"><h3>Jour de repos</h3><p>Aucun planning ni trajet ne sera calculé pour le '+esc(date)+'. Ce jour n’est pas coché dans vos jours travaillés.</p><p>Choisissez une autre date ou modifiez vos jours dans Mes critères → Disponibilités.</p></div>';$('#planningProgress').textContent='Jour de repos · planification désactivée.';if(activeTransitJob)fetch('/api/transit/jobs/'+activeTransitJob+'/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});return;}
if($('#planningProgress').textContent.startsWith('Jour de repos'))$('#planningProgress').textContent='';
if(!plan&&planningMode==='confirmed'&&(result?.pendingDecision||!planningTasks().length)){$('#timeline').innerHTML=`<div class="empty"><h3>${result?.pendingDecision?'Choisissez les missions à conserver.':'Aucune mission confirmée pour cette journée.'}</h3><p>${result?.pendingDecision?'Dans la liste ci-dessus, confirmez ✓ ou annulez × les missions en attente de cette journée. Le planning sera ensuite calculé avec toutes celles confirmées.':'Vos réservations restent toutes visibles ci-dessus. Vous pouvez aussi préparer des propositions avant réservation avec le sélecteur.'}</p></div>`;return;}
if(!plan){$('#timeline').innerHTML=`<div class="empty"><h3>${p.placeResolved===false?'Point de départ à vérifier.':p.mobility==='transit'&&!currentTransit()?'Horaires de transport à calculer.':result?.fixedConflict?'Vos engagements ne tiennent pas dans ces limites.':'Aucun planning compatible.'}</h3><p>${p.placeResolved===false?'Ouvrez Mes critères → Trajets et zones et sélectionnez une commune dans les résultats. Le nom du lieu ne suffit pas à modifier les coordonnées.':p.mobility==='transit'&&!currentTransit()?'Cliquez sur « Calculer avec les horaires ». Les trajets seront calculés avec votre connexion PRIM ou SNCF et vos critères.':result?.fixedConflict?'Vérifiez les coordonnées, les demandes en attente, les pauses et les trajets.':isDemo?'Aucun exemple ne convient à ces limites. Vous pouvez changer de ville de démonstration, ajuster vos critères ou importer des missions réelles.':'Essayez une autre date, assouplissez vos critères ou importez de nouvelles missions.'}</p></div>`;return;}
const status={available:'Sélectionnée',pending:'Demande en attente',confirmed:'Confirmée'};let html=`<div class="start-end"><strong>${hhmm(plan.seq[0].depart)}</strong><span>Départ · ${esc(p.origin)}</span></div>`;
plan.seq.forEach((x,i)=>{const wait=i?x.depart-plan.seq[i-1].finish:0;html+=`<div class="leg">${x.leg.minutes} min de trajet ${x.leg.provider?'· '+(x.leg.provider==='idfm'?'IDFM / PRIM':x.leg.provider==='ign'?'IGN · durée théorique':'SNCF'):x.leg.estimated?'estimé':'renseigné'}${p.mobility==='transit'?'':` · ${Math.round(x.leg.km)} km`} ${i?`· ${wait} min entre les missions avant le trajet, dont ${p.gap} min de marge`:''}</div>${journeyDetails(x.leg)}<div class="timeline-row"><div class="time">${hhmm(x.begin)}<br><span class="muted">${hhmm(x.finish)}</span></div><div class="mission"><div class="mission-top"><span class="badge ${x.task.status==='pending'?'pending':''}">${status[x.task.status]}</span><div class="mission-controls"><strong>${money(x.task.pay)}</strong>${statusActions(x.task)}</div></div><h3>${esc(x.task.title)}</h3><p>${esc(x.task.address)} · ${esc(x.task.department)}</p><p>${x.task.duration} min de montage + ${x.finish-x.begin-x.task.duration} min de prudence</p><button class="text" data-edit="${esc(x.task.id)}">Voir / modifier →</button>${portalLink(x.task)}</div></div>`;});if(p.returnHome)html+=`<div class="leg">Retour · ${plan.back.minutes} min ${plan.back.provider?(plan.back.provider==='ign'?'· IGN, sans trafic temps réel':'· horaires API'):plan.back.estimated?'estimés':'renseignés'}</div>${journeyDetails(plan.back)}`;html+=`<div class="start-end"><strong>${hhmm(plan.end)}</strong><span>${p.returnHome?'Retour · '+esc(p.origin):'Fin de la dernière mission'}</span></div><p class="muted">${planningMode==='confirmed'?'Toutes les missions confirmées de cette journée sont incluses.':result.approximate?'Recherche limitée sur un grand volume : meilleur résultat trouvé, sans garantie d’optimalité.':'Combinaisons compatibles comparées selon votre priorité.'} Les disponibilités et l’attribution doivent être confirmées sur Taskrabbit.</p><p class="muted">✓ Mission déjà confirmée · × Mission déjà annulée dans Taskrabbit. Ces boutons mettent à jour votre planning local et recalculent les trajets.</p>`;$('#timeline').innerHTML=html;bindEdit();}

function renderReservations(){const all=reservations(tasks),day=reservationDay(tasks,date);$('#reservationSummary').textContent=all.length+' missions suivies · Pour le '+date+' : '+day.pending.length+' à valider, '+day.confirmed.length+' confirmées';$('#reservationList').innerHTML=all.length?all.map(t=>`<article class="task-card reservation-card"><div class="body"><span class="eyebrow">${esc(t.date)} · ${esc(t.time)} · #${esc(t.id)}</span><h3>${esc(t.title)}</h3><p>${esc(t.address)} · ${t.duration} min</p><span class="badge ${t.status==='pending'?'pending':''}">${t.cancelledLocally?'Annulée':t.status==='confirmed'?'Confirmée':'À valider'}</span></div><div class="amount">${money(t.pay)}</div>${statusActions(t)}<button class="text" data-edit="${esc(t.id)}">Modifier</button>${portalLink(t)}</article>`).join(''):'<p class="muted">Aucune réservation renseignée. Pour une mission déjà réservée dans Taskrabbit, ouvrez Missions disponibles → Modifier et choisissez « Demande en attente » ou « Confirmée ».</p>';bindEdit();}
function portalLink(t){return /^\d+$/.test(t.id)?`<a class="text" target="_blank" rel="noopener noreferrer" href="https://taskrabbitlimited.outsystemsenterprise.com/TaskPortal/task_page?distance=0&location_given=false&taskid=${encodeURIComponent(t.id)}">Ouvrir sur Taskrabbit ↗</a>`:'';}
function renderTasks(){const query=$('#search').value.toLowerCase(),filter=$('#taskFilter').value;const shown=tasks.filter(t=>(t.title+' '+t.address+' '+t.id).toLowerCase().includes(query)&&(filter==='all'||filter==='eligible'&&!reasons(t,p,date).length||filter===t.status));$('#taskList').innerHTML=shown.length?shown.map(t=>{const r=reasons(t,p,date);return `<article class="task-card"><div class="body"><span class="eyebrow">${esc(t.brand)} · ${esc(t.date)} À ${esc(t.time)}</span><h3>${esc(t.title)}</h3><p>${esc(t.address)} · ${esc(t.department)} · ${t.duration} min</p><span class="badge ${t.status==='pending'?'pending':''}">${t.status==='unavailable'&&t.cancelledLocally?'Annulée':({available:'Disponible',pending:'En attente',confirmed:'Confirmée',unavailable:'Indisponible'})[t.status]}</span>${r.length?`<p class="reasons">${r.map(esc).join(' · ')}</p>`:''}</div><div class="amount">${money(t.pay)}</div>${statusActions(t)}<button class="secondary" data-edit="${esc(t.id)}">Modifier</button>${portalLink(t)}</article>`;}).join(''):'<div class="empty">Aucune mission dans cette sélection.</div>';bindEdit();}

async function runTransitCalculation(ui){if(!isWorkingDate(date,p)){calculate();return;}if(planningMode==='confirmed'&&(reservationDay(tasks,date).pending.length||!planningTasks().length)){calculate();return;}const progress=t=>{const el=ui.root.querySelector('#transitProgress');if(el)el.textContent=t;$('#planningProgress').textContent=t;};const button=ui.root.querySelector('#calculateTransit'),cancel=ui.root.querySelector('#cancelTransit');if(activeTransitJob){progress('Un calcul est déjà en cours.');return;}try{if(!$('#prefs').reportValidity())return;applyPrefs();if(!isWorkingDate(date,p)){calculate();return;}const snapshot=JSON.stringify({p,date,tasks,planningMode});progress('Calcul des trajets et des horaires en cours…');$('#calculate').disabled=true;button.disabled=true;ui.root.querySelectorAll('[data-mobility]').forEach(b=>b.disabled=true);const response=await fetch('/api/transit/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p,date,tasks:planningTasks()})});const data=await response.json();if(!response.ok)throw Error(data.error||'Impossible de démarrer le calcul.');activeTransitJob=data.id;cancel.hidden=false;cancel.onclick=()=>fetch('/api/transit/jobs/'+data.id+'/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});for(;;){await new Promise(r=>setTimeout(r,1000));const response=await fetch('/api/transit/jobs/'+data.id);if(!response.ok)throw Error('Le serveur de calcul ne répond plus.');const job=await response.json();progress(job.completed+' / '+job.total+' trajets calculés · '+job.cached+' en cache');if(job.state==='error'||job.state==='cancelled')throw Error(job.error||'Calcul arrêté.');if(job.state==='done'){if(snapshot!==JSON.stringify({p,date,tasks,planningMode}))throw Error('Les critères ou les missions ont changé. Relancez le calcul.');transitMatrix=job.result.matrix;calculate();view('plan');toast('Horaires calculés. '+job.unavailable+' trajet(s) incompatibles exclus.');break;}}}catch(e){progress(e.message);toast(e.message);}finally{activeTransitJob=null;$('#calculate').disabled=false;renderPlan();if(button)button.disabled=!isWorkingDate(date,p);if(cancel)cancel.hidden=true;ui.root.querySelectorAll('[data-mobility]').forEach(b=>b.disabled=false);}}
function statusActions(t){return `<div class="task-status-actions" role="group" aria-label="Suivi de ${esc(t.title)}"><button type="button" class="task-confirm ${t.status==='confirmed'?'is-confirmed':''}" data-task-status="confirmed" data-task-id="${esc(t.id)}" aria-label="Marquer comme confirmée : ${esc(t.title)}" aria-pressed="${t.status==='confirmed'}" title="Marquer comme confirmée dans votre planning">✓</button><button type="button" class="task-cancel ${t.status==='unavailable'?'is-cancelled':''}" data-task-status="unavailable" data-task-id="${esc(t.id)}" aria-label="Marquer comme annulée : ${esc(t.title)}" aria-pressed="${t.status==='unavailable'}" title="Marquer comme annulée dans votre planning" >×</button></div>`;}
let statusRecalcTimer;
function scheduleStatusRecalculation(){clearTimeout(statusRecalcTimer);statusRecalcTimer=setTimeout(()=>{if(activeTransitJob){scheduleStatusRecalculation();return;}if(isWorkingDate(date,p)&&p.mobility==='transit'&&planningMode==='confirmed'&&!reservationDay(tasks,date).pending.length&&planningTasks().length)runTransitCalculation(transportPicker);},400);}
function changeTaskStatus(id,status){const task=tasks.find(t=>t.id===id);if(!task||!['confirmed','unavailable'].includes(status))return;if(task.status===status){toast(status==='confirmed'?'Cette mission est déjà confirmée.':'Cette mission est déjà annulée. Cliquez sur ✓ pour corriger ce choix.');return;}const previous={status:task.status,cancelledLocally:task.cancelledLocally};planningMode='confirmed';task.status=status;task.cancelledLocally=status==='unavailable';calculate();scheduleStatusRecalculation();let notice=$('#statusNotice');if(!notice){notice=document.createElement('div');notice.id='statusNotice';notice.className='status-notice';notice.setAttribute('role','status');$('#planView').before(notice);}notice.hidden=false;notice.textContent=status==='confirmed'?'Mission confirmée dans votre planning.':'Mission annulée : retirée du planning.';const undo=document.createElement('button');undo.type='button';undo.className='secondary';undo.textContent='Annuler cette modification';undo.onclick=()=>{const current=tasks.find(t=>t.id===id);if(!current)return;Object.assign(current,previous);notice.hidden=true;calculate();scheduleStatusRecalculation();toast('Modification annulée. Planning recalculé.');};notice.append(undo);clearTimeout(changeTaskStatus.timer);changeTaskStatus.timer=setTimeout(()=>notice.hidden=true,30000);}
function bindEdit(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-task-status]').forEach(b=>b.onclick=()=>changeTaskStatus(b.dataset.taskId,b.dataset.taskStatus));}
const taskFields=[['id','Identifiant','text'],['title','Meubles / description','text'],['date','Date','date'],['time','Heure fixe de début','time'],['duration','Durée de montage (min)','number',1,1440],['pay','Paiement total (€)','number',0,10000,.01],['address','Adresse / commune','text'],['department','Département','text'],['brand','Marque','text'],['lat','Latitude','number',-90,90,.000001],['lon','Longitude','number',-180,180,.000001]];
function edit(id){editing=id||null;const t=id?tasks.find(t=>t.id===id):{id:`M${Date.now()}`,title:'',date,time:'09:00',duration:60,pay:50,address:'',department:'',brand:'IKEA',lat:'',lon:'',status:'available'};$('#taskTitle').textContent=id?'Modifier la mission':'Ajouter une mission';$('#taskFields').innerHTML=`<div class="field-grid">${taskFields.map(f=>field(f,t[f[0]]??'')).join('')}<label>Statut suivi manuellement<select name="status">${['available','pending','confirmed','unavailable'].map(s=>`<option value="${s}" ${s===t.status?'selected':''}>${({available:'Disponible',pending:'Demande en attente',confirmed:'Confirmée',unavailable:'Indisponible'})[s]}</option>`).join('')}</select></label></div><p class="muted">Ce formulaire change uniquement votre liste locale. Il ne demande ni ne confirme une mission sur Taskrabbit.</p>`;$('#taskDialog').showModal();}
$('#taskForm').onsubmit=e=>{e.preventDefault();try{const raw=Object.fromEntries(new FormData(e.target));if(raw.lat==='')raw.lat=null;if(raw.lon==='')raw.lon=null;const updated=normalizeTasks([...tasks.filter(t=>t.id!==editing),raw]);if(editing){matrix=Object.fromEntries(Object.entries(matrix).filter(([k])=>!k.split(">").includes(editing)));}tasks=updated;$('#taskDialog').close();calculate();toast('Mission enregistrée localement.');}catch(e){toast(e.message);}};
$('#closeTask').onclick=()=>$('#taskDialog').close();$('#add').onclick=()=>edit();$('#search').oninput=renderTasks;$('#taskFilter').onchange=renderTasks;
$('#date').value=date;$('#date').onchange=()=>{if(!$('#date').value){$('#date').value=date;toast('Choisissez une date valide.');return;}date=$('#date').value;transitMatrix={};calculate();};$('#planningMode').value=planningMode;$('#planningMode').onchange=()=>{planningMode=$('#planningMode').value;calculate();};$('#objective').value=p.objective;$('#objective').onchange=()=>{p.objective=$('#objective').value;calculate();};$('#calculate').onclick=()=>{if(p.mobility==='transit'){runTransitCalculation(transportPicker);}else{calculate();toast('Planning recalculé. Aucune demande envoyée.');}};
function applyPrefs(){const data=new FormData($('#prefs')),next={...p};groups.flatMap(g=>g[1]).forEach(([name,,type])=>next[name]=type==='checkbox'?data.has(name):type==='number'?Number(data.get(name)):data.get(name));next.workDays=data.getAll('workDays').map(Number);Object.assign(next,zonePicker.getValue(),transportPicker.getValue());validatePrefs(next);if(next.lat!==p.lat||next.lon!==p.lon)matrix=Object.fromEntries(Object.entries(matrix).filter(([k])=>!k.split('>').includes('home')));p=next;$('#objective').value=p.objective;save();}
let criteriaTimer;
function synchronizePrefs(){if(!zonePicker||!transportPicker)return true;try{if(!$('#prefs').checkValidity())throw Error('Complétez les critères avec des valeurs valides.');applyPrefs();calculate();$('#criteriaStatus').textContent='Critères enregistrés automatiquement. Le planning et les règles sont à jour.';return true;}catch(e){$('#criteriaStatus').textContent=e.message;return false;}}
function scheduleCriteria(){clearTimeout(criteriaTimer);criteriaTimer=setTimeout(synchronizePrefs,150);}
$('#prefs').addEventListener('criteriachange',scheduleCriteria);
for(const event of ['input','change'])$('#prefs').addEventListener(event,e=>{if(e.target.matches('[name],[data-transport],#radiusNumber,#radiusRange'))scheduleCriteria();});
$('#prefs').onsubmit=e=>{e.preventDefault();try{if(synchronizePrefs()){view('plan');toast('Critères enregistrés sur cet appareil.');}}catch(e){toast(e.message);}};
$('#reset').onclick=()=>{p={...defaults};transitMatrix={};$('#objective').value=p.objective;settings();calculate();toast('Critères réinitialisés.');};
$('#importButton').onclick=()=>$('#importDialog').showModal();$('#connectionButton').onclick=()=>$('#connectDialog').showModal();$('#openPortal').onclick=()=>{const email=$('#email').value.trim();if(email&&$('#email').checkValidity()){navigator.clipboard.writeText(email).then(()=>toast('Email copié. Collez-le dans le portail officiel.')).catch(()=>toast('Renseignez votre email directement sur le portail officiel.'));}window.open('https://taskrabbitlimited.outsystemsenterprise.com/TaskPortal/?source=FR','_blank','noopener');};
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(f){if(f.size>2000000)return toast('Fichier trop volumineux (2 Mo maximum).');$('#importText').value=await f.text();}};
$('#importConfirm').onclick=()=>{try{const parsed=JSON.parse($('#importText').value),incoming=normalizeTasks(Array.isArray(parsed)?parsed:parsed.tasks);const merged=mergeOffers(isDemo?[]:tasks,incoming,{preserveIncomingStatus:true});tasks=merged.tasks;matrix={};transitMatrix={};isDemo=false;save();$('#importDialog').close();settings();calculate();toast(merged.added.length+' nouvelles missions. Statuts suivis conservés.');}catch(e){toast(e.message);}};
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('#exportTasks').onclick=()=>download('taskpilot-missions.json',JSON.stringify(tasks,null,2),'application/json');
$('#saveMatrix').onclick=()=>{try{const next=JSON.parse($('#matrixText').value||'{}');if(!next||Array.isArray(next)||typeof next!=='object')throw Error('Objet JSON attendu.');for(const [key,v]of Object.entries(next)){if(!/^[^>]+>[^>]+$/.test(key)||!v||!Number.isFinite(v.minutes)||!Number.isFinite(v.km)||v.minutes<0||v.km<0)throw Error('Chaque trajet doit indiquer minutes et km positifs.');}matrix=Object.fromEntries(Object.entries(next).map(([key,val])=>[key,{...val,mode:p.mobility}]));$('#matrixDialog').close();calculate();toast('Durées vérifiées enregistrées.');}catch(e){toast(e.message);}};
const icalEscape=s=>String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
$('#ics').onclick=()=>{const plan=result?.plans[selected];if(!plan)return;const stamp=m=>date.replaceAll('-','')+'T'+hhmm(m).replace(':','')+'00';const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//TaskPilot//FR','CALSCALE:GREGORIAN'];for(const x of plan.seq)lines.push('BEGIN:VEVENT',`UID:${icalEscape(x.task.id)}-${date}@taskpilot.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART;TZID=Europe/Paris:${stamp(x.begin)}`,`DTEND;TZID=Europe/Paris:${stamp(x.finish)}`,`SUMMARY:${icalEscape((x.task.status==='confirmed'?'Confirmée':'Prévisionnel')+' · '+x.task.title)}`,`LOCATION:${icalEscape(x.task.address)}`,x.task.status==='confirmed'?'STATUS:CONFIRMED':'STATUS:TENTATIVE','DESCRIPTION:Planning local. Vérifier attribution sur Taskrabbit.','END:VEVENT');for(const [i,x]of plan.seq.entries()){const leg=x.leg,from=leg.departure??x.depart,to=leg.arrival??x.begin;if(to>from)lines.push('BEGIN:VEVENT',`UID:travel-${i}-${date}@taskpilot.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART;TZID=Europe/Paris:${stamp(from)}`,`DTEND;TZID=Europe/Paris:${stamp(to)}`,`SUMMARY:${icalEscape('Trajet · '+transportNames[p.mobility])}`,`DESCRIPTION:${icalEscape((leg.steps||[]).map(s=>s.line?s.mode+' '+s.line+' '+s.from+' → '+s.to:'Marche / attente').join(' ; ')||'Temps de trajet estimé')}`,'STATUS:TENTATIVE','END:VEVENT');}if(p.returnHome){const from=plan.back.departure??plan.seq.at(-1).finish;if(plan.end>from)lines.push('BEGIN:VEVENT',`UID:return-${date}@taskpilot.local`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART;TZID=Europe/Paris:${stamp(from)}`,`DTEND;TZID=Europe/Paris:${stamp(plan.end)}`,'SUMMARY:Trajet de retour','STATUS:TENTATIVE','END:VEVENT');}lines.push('END:VCALENDAR');download(`planning-${date}.ics`,lines.join('\r\n')+'\r\n','text/calendar');};
$('#demoCity').value=demoCity;$('#loadDemo').onclick=()=>{if(!isDemo)return;demoCity=$('#demoCity').value;tasks=demo(date,demoCity);matrix={};transitMatrix={};save();settings();calculate();view('plan');toast('Exemples fictifs chargés. Vos critères sont conservés.');};
settings();calculate();

setupOffers({getTasks:()=>tasks,setTasks:next=>{tasks=normalizeTasks(next);transitMatrix={};save();calculate();},onSnapshot:snapshot=>{const merged=mergeOffers(isDemo?[]:tasks,snapshot.tasks,{complete:true,seenAt:snapshot.seenAt});tasks=merged.tasks;isDemo=false;save();settings();calculate();if(merged.added.length||merged.changed.length)toast(merged.added.length+' nouvelles offres · '+merged.changed.length+' modifications. Recalculez les trajets.');}});

setupRequestQueue({getPlan:()=>result?.plans[selected],getTasks:()=>tasks,setTasks:next=>{tasks=normalizeTasks(next);save();calculate();},isDemo:()=>isDemo});

setInterval(()=>{const plan=result?.plans[selected];if(p.mobility==='transit'&&plan&&!activeTransitJob&&[...plan.seq.map(x=>x.leg),plan.back].some(leg=>leg?.provider&&leg.fetchedAt<=Date.now()-600000)){calculate();$('#planningProgress').textContent='Horaires périmés : cliquez sur Calculer avec les horaires pour les actualiser.';}},30000);
