import {accountStorage} from './account-storage.mjs';
export function setupBot({getUser,updateUser}){
 const $=s=>document.querySelector(s);let status=null,busy=false,unavailable=false;
 function draw(){const user=getUser();$('#taskrabbitVerifiedStatus').textContent=!user.taskrabbitEmail?'Enregistrez d’abord votre adresse Taskrabbit ci-dessus.':user.taskrabbitVerified?'Adresse Taskrabbit vérifiée.':'Vérifiez cette adresse avant les demandes automatiques.';$('#verifyTaskrabbit').hidden=user.taskrabbitVerified;$('#verifyTaskrabbit').disabled=!user.taskrabbitEmail;
  $('#botStatus').textContent=unavailable?'Bot autonome momentanément indisponible':!status?'Vérification de la disponibilité…':status.pilot?status.pilot.used>=status.pilot.maxRequests?'Essai personnel terminé':user.automationEnabled?'Essai personnel activé':'Essai personnel à activer':!status.available?'Activation en attente de l’autorisation Taskrabbit':user.automationEnabled?'Bot autonome activé':'Bot autonome en pause';
  $('#botAuthorization').hidden=status?.available===true;$('#botToggle').disabled=(!status?.available&&!user.automationEnabled)||busy;$('#botToggle').textContent=user.automationEnabled?'Mettre le bot en pause':'Activer les demandes automatiques';
  $('#botConsentLabel').hidden=user.automationEnabled;$('#botBudget').textContent=status?'Budget navigateur partagé restant : '+Math.floor(status.remainingSeconds/60)+' min '+status.remainingSeconds%60+' s. Renouvellement à 00:00 UTC.':'';
  $('#botActivity').textContent=unavailable?'Le statut serveur ne peut pas être vérifié.':(status?.pilot?'Contrôles le '+status.pilot.runDate+' à '+getUser().monitoring.times.join(' et ')+' (Paris), pour les missions du '+status.pilot.targetDate+'. '+status.pilot.used+' / '+status.pilot.maxRequests+' demande(s) envoyée(s) ou préparée(s). ':'')+(status?.message||'Aucune demande automatique envoyée.');$('#botHistory').replaceChildren(...(status?.history||[]).slice(0,5).map(item=>{const li=document.createElement('li');li.textContent=new Date(item.at).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})+' · '+item.message;return li;}));
  const foot=document.querySelector('.aside-foot small');if(foot)foot.textContent=unavailable?'Bot autonome indisponible':status?.pilot?.used>=status?.pilot?.maxRequests?'Essai personnel terminé':user.automationEnabled&&status?.available?'Demandes automatiques activées':'Demandes automatiques en pause';
 }
 async function post(action,data={}){const response=await fetch('/api/account/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Service indisponible.');return result;}
 $('#verifyTaskrabbit').onclick=async()=>{const button=$('#verifyTaskrabbit');button.disabled=true;try{$('#botMessage').textContent=(await post('taskrabbit-verification')).message;}catch(e){$('#botMessage').textContent=e.message;}finally{button.disabled=false;}};
 $('#botToggle').onclick=async()=>{if(busy)return;busy=true;draw();try{const result=await post('automation',{enabled:!getUser().automationEnabled,acceptTerms:$('#botConsent').checked});updateUser(result.user);$('#botMessage').textContent=result.user.automationEnabled?'Le serveur vérifiera les offres aux créneaux choisis, dans la limite du quota partagé.':'Les nouvelles demandes automatiques sont arrêtées. Les demandes déjà envoyées restent à gérer sur Taskrabbit.';}catch(e){$('#botMessage').textContent=e.message;}finally{busy=false;draw();}};
 async function refresh(){try{const response=await fetch('/api/bot/status');if(!response.ok)throw Error();status=await response.json();unavailable=false;if($('#settingsView').hidden&&!document.querySelector('dialog[open]'))await accountStorage.refresh();}catch{status=null;unavailable=true;}draw();}
 window.addEventListener('taskpilot-profile-updated',draw);draw();refresh();const timer=setInterval(refresh,15000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
}
