import {privatePilot,parisDay} from './pilot-policy.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaults,tomorrow} from './model.mjs';
import {freeBudget,reserveBrowser,releaseBrowser,botSettings,prepareBotOffers,safeGeocode,chooseBotTask,sameOffer,botEdges} from './bot-policy.mjs';
import {browserSession,requestOffer} from './cloud/portal-browser.mjs';
import {createAccountCore} from './account-core.mjs';
import {Readable} from 'node:stream';
const p={...defaults,workDays:[1,2,3,4,5,6,7],lunch:false,returnHome:false,minRate:0,minPay:0,overrun:0,zoneMode:'all',maxPending:2},date=tomorrow();
const task={id:'1001',date,time:'09:00',duration:60,pay:80,address:'12 rue Test, 69001',lat:45.764,lon:4.8357,brand:'IKEA',status:'available'};
const monitoring={enabled:true,mode:'all'},context={email:'owner@example.test',monitoring,state:{'taskpilot-v1':JSON.stringify({prefs:p,tasks:[]})}};
const leg={available:true,minutes:10,km:1,provider:'ign',mode:'car',signature:JSON.stringify(['car',p.lat,p.lon,task.lat,task.lon]),fetchedAt:Date.now()};
test('Bot gratuit : budget partagé, lancements espacés et aucun dépassement',()=>{const now=Date.parse('2026-10-03T11:00:00Z');let b=reserveBrowser(null,now);assert.throws(()=>reserveBrowser(b,now+19999),/launch-spacing/);for(let i=1;i<5;i++)b=reserveBrowser(b,now+i*20000);assert.equal(b.used,450);assert.throws(()=>reserveBrowser(b,now+100000),/quota/);assert.equal(releaseBrowser(b,12,false,now).used,450);assert.equal(releaseBrowser(b,12,true,now).used,372);});
test('Bot gratuit : remise à zéro UTC et aucune restitution traversant minuit',()=>{const now=Date.parse('2026-10-03T23:59:55Z'),b=reserveBrowser(null,now);assert.equal(freeBudget(b,now+10000).used,0);assert.equal(releaseBrowser(b,3,true,now+10000).used,90);});
test('Bot : adresse de test, pause, jours off et vélo refusés avant consultation',()=>{assert.throws(()=>botSettings({...context,email:'memmoudkamel01@gmail.com'}));assert.throws(()=>botSettings({...context,monitoring:{enabled:false}}));for(const changes of [{workDays:[]},{mobility:'bike'},{maxPending:0}])assert.throws(()=>botSettings({...context,state:{'taskpilot-v1':JSON.stringify({prefs:{...p,...changes}})}}));});
test('Bot : démo ou critères absents ne permettent aucune demande',()=>{assert.throws(()=>botSettings({...context,state:{}}));assert.throws(()=>botSettings({...context,state:{'taskpilot-v1':JSON.stringify({prefs:p,isDemo:true})}}));});
test('Bot : demandes en attente conservées même si elles disparaissent du portail',()=>{const c={...context,state:{'taskpilot-v1':JSON.stringify({prefs:p,tasks:[{...task,status:'pending'}]})}};const result=prepareBotOffers(c,[{...task,id:'1002',time:'14:00'}]);assert.equal(result.tasks.find(t=>t.id===task.id).status,'pending');});
test('Bot : géocodage ambigu, mauvais code postal ou absence de précision refusés',()=>{const point={score:.95,postcode:'69001',type:'street',lat:45.7,lon:4.8};assert.equal(safeGeocode(task.address,[point]),point);assert.equal(safeGeocode(task.address,[point,{...point,score:.94}]),null);assert.equal(safeGeocode(task.address,[{...point,postcode:'75001'}]),null);assert.equal(safeGeocode(task.address,[{...point,type:'municipality'}]),null);});
test('Bot : aucune sélection avec une estimation de distance sans route calculée',()=>{assert.equal(chooseBotTask([task],p,date,{}),null);assert.equal(chooseBotTask([task],p,date,{'home>1001':leg}).id,task.id);assert.equal(chooseBotTask([task],p,date,{'home>1001':leg},{'1001':{state:'uncertain'}}),null);});
test('Bot : chevauchement avec une mission confirmée ou plafond atteint refuse la demande',()=>{const fixed={...task,id:'1002',status:'confirmed'};assert.equal(chooseBotTask([task,fixed],p,date,{'home>1001':leg,'home>1002':leg}),null);assert.equal(chooseBotTask([task],{...p,maxPending:0},date,{'home>1001':leg}),null);});
test('Bot : transport sans horaires et routes indisponibles ne provoquent aucune demande',()=>{assert.equal(chooseBotTask([task],{...p,mobility:'transit'},date,{}),null);assert.equal(chooseBotTask([task],p,date,{'home>1001':{...leg,available:false}}),null);});
test('Bot : retour absent, marge et créneaux indisponibles bloquent les demandes',()=>{const matrix={'home>1001':leg};assert.equal(chooseBotTask([task],{...p,returnHome:true},date,matrix),null);assert.equal(chooseBotTask([task],{...p,blocked:'08:50-10:00'},date,matrix),null);const edges=botEdges([task,{...task,id:'1002',time:'10:10'}],{...p,gap:20},date);assert.equal(edges.some(e=>e.from.id==='1001'&&e.to.id==='1002'),false);});
test('Bot : détails frais doivent correspondre à l’adresse, au compte, au prix et à l’horaire',()=>{const fresh={...task,email:context.email,street:'12 rue Test',postcode:'69001'};assert.equal(sameOffer(task,fresh,context.email),true);for(const changes of [{street:'Autre rue'},{postcode:'75001'},{pay:81},{time:'10:00'},{email:'another@example.test'},{duration:61},{brand:'other'},{id:'1002'}])assert.equal(sameOffer(task,{...fresh,...changes},context.email),false);});
test('Navigateur : fermeture explicite et comptabilisation même en cas d’erreur',async()=>{let closes=0,accounting;const client={launch:async()=>({close:async()=>{closes++;}})};await assert.rejects(browserSession({},async()=>{throw Error('Portail refusé');},async(...args)=>{accounting=args;},{client}),/Portail refusé/);assert.equal(closes,1);assert.equal(accounting[1],true);});
test('Navigateur : délai dépassé arrête la session et ne libère pas une fermeture incertaine',async()=>{let closes=0,accounting;const client={launch:async()=>({close:async()=>{closes++;throw Error('CDP déconnecté');}})};await assert.rejects(browserSession({},()=>new Promise(()=>{}),async(...args)=>{accounting=args;},{client,timeoutMs:10}),/délai/);assert.ok(closes>=1);assert.equal(accounting[1],false);});
test('Navigateur : lancement tardif fermé sans consultation du portail',async()=>{let close=0,operations=0;const client={launch:()=>new Promise(r=>setTimeout(()=>r({close:async()=>{close++;}}),30))};await assert.rejects(browserSession({},()=>{operations++;return new Promise(()=>{});},async()=>{}, {client,timeoutMs:5}));await new Promise(r=>setTimeout(r,40));assert.ok(close>=1);assert.equal(operations,0);});
test('Demande : compte de test refusé avant toute ouverture de navigateur',async()=>{await assert.rejects(requestOffer({newPage:()=>assert.fail('Navigation interdite')},'memmoudkamel01@gmail.com',task,()=>assert.fail('Demande interdite')),/test/);});
function fakePortal({detail={},ack=true}={}){const trace=[];const page={setDefaultTimeout(){},setDefaultNavigationTimeout(){},goto:async()=>{},waitForSelector:async()=>{},type:async()=>{},evaluate:async fn=>{if(fn.name==='readDetail')return {...task,email:context.email,street:'12 rue Test',postcode:'69001',canRequest:true,...detail};if(fn.toString().includes('Demande indisponible'))trace.push('click');},waitForFunction:async fn=>{if(fn.toString().includes('document.body.innerText')&&!ack)throw Error('Retour inconnu');}};return {browser:{newPage:async()=>page},trace};}
test('Demande : état incertain enregistré avant le clic, puis en attente après accusé',async()=>{const f=fakePortal();assert.equal(await requestOffer(f.browser,context.email,task,async()=>{f.trace.push('persist');}),'submitted');assert.deepEqual(f.trace,['persist','click']);});
test('Demande : retour inconnu ne provoque pas un second clic',async()=>{const f=fakePortal({ack:false});assert.equal(await requestOffer(f.browser,context.email,task,async()=>{f.trace.push('persist');}),'uncertain');assert.deepEqual(f.trace,['persist','click']);});
test('Demande : détails modifiés ou autorisation révoquée empêchent tout clic',async()=>{for(const detail of [{pay:99},{email:'wrong@example.test'},{street:'Autre rue'},{canRequest:false}]){const f=fakePortal({detail});await assert.rejects(requestOffer(f.browser,context.email,task,()=>assert.fail('Ne pas préparer une mission modifiée')));assert.deepEqual(f.trace,[]);}const f=fakePortal();await assert.rejects(requestOffer(f.browser,context.email,task,async()=>{throw Error('Pause');}),/Pause/);assert.deepEqual(f.trace,[]);});
async function accountFixture({approved=true,pilotFor,email='login@example.test',taskrabbitEmail='rabbit@example.test'}={}){let database;const sent=[],storage={load:async()=>database,save:async d=>{database=structuredClone(d);}};const core=await createAccountCore({storage,pilotFor,automationAvailable:approved,mailer:{configured:true,send:async message=>{sent.push(message);}}});let cookie='';async function call(action,data,method='POST'){const req=Readable.from([Buffer.from(JSON.stringify(data||{}))]);req.method=method;req.headers={host:'127.0.0.1:4173',origin:'http://127.0.0.1:4173','content-type':'application/json',cookie};req.socket={remoteAddress:'127.0.0.1'};let status,headers,payload;await core.api(req,{writeHead(s,h){status=s;headers=h;},end(s){payload=JSON.parse(s);}},new URL('http://127.0.0.1:4173/api/account/'+action));if(headers?.['Set-Cookie'])cookie=headers['Set-Cookie'].split(';')[0];return {status,payload};}await call('register',{email,taskrabbitEmail,password:'Only-test-password-123',state:{'taskpilot-v1':JSON.stringify({prefs:p,tasks:[]})}});await core.waitForMail();await call('verify-email',{token:sent[0].token});await call('login',{email,password:'Only-test-password-123'});await call('monitoring',{enabled:true,mode:'all'});return {call,sent,core,database:()=>database};}
test('Compte bot : adresse distincte vérifiée avec un jeton haché et usage unique',async()=>{const f=await accountFixture();assert.equal((await f.call('automation',{enabled:true,acceptTerms:true})).status,400);await f.call('taskrabbit-verification');await f.core.waitForMail();const message=f.sent.find(m=>m.purpose==='taskrabbit');assert.equal(message.to,'rabbit@example.test');assert.equal(JSON.stringify(f.database()).includes(message.token),false);assert.equal((await f.call('verify-email',{token:message.token})).status,400);assert.equal((await f.call('verify-taskrabbit',{token:message.token})).status,200);assert.equal((await f.call('verify-taskrabbit',{token:message.token})).status,400);assert.equal((await f.call('automation',{enabled:true,acceptTerms:false})).status,400);assert.equal((await f.call('automation',{enabled:true,acceptTerms:true})).status,200);assert.equal(f.core.botUsers().length,1);});
test('Compte bot : changement d’adresse désactive le bot et invalide les anciens liens',async()=>{const f=await accountFixture();await f.call('taskrabbit-verification');await f.core.waitForMail();const token=f.sent.find(m=>m.purpose==='taskrabbit').token;await f.call('profile',{taskrabbitEmail:'new@example.test'});assert.equal((await f.call('verify-taskrabbit',{token})).status,400);assert.equal(f.core.botUsers().length,0);assert.equal((await f.call('me',{},'GET')).payload.user.taskrabbitVerified,false);});
test('Compte bot : autorisation propriétaire requise, pause toujours disponible',async()=>{const f=await accountFixture({approved:false,taskrabbitEmail:'login@example.test'});assert.equal((await f.call('me',{},'GET')).payload.user.taskrabbitVerified,true);assert.equal((await f.call('automation',{enabled:true,acceptTerms:true})).status,409);assert.equal((await f.call('automation',{enabled:false})).status,200);assert.deepEqual(f.core.botUsers(),[]);});
test('Compte bot : e-mail vérifié du compte ne contourne jamais la protection de test',async()=>{const f=await accountFixture({email:'memmoudkamel01@gmail.com',taskrabbitEmail:'memmoudkamel01@gmail.com'});assert.equal((await f.call('automation',{enabled:true,acceptTerms:true})).status,400);assert.deepEqual(f.core.botUsers(),[]);});
test('Compte bot : modifications concurrentes empêchent le remplacement du planning',async()=>{const f=await accountFixture({taskrabbitEmail:'login@example.test'});await f.call('automation',{enabled:true,acceptTerms:true});const owner=f.core.botUsers()[0].id,old=f.core.botContext(owner);await f.call('state',{revision:old.revision,state:{...old.state,'taskpilot-alerts':'true'}},'PUT');await assert.rejects(f.core.botSave(owner,old.revision,old.state),/changé/);assert.equal(f.core.botContext(owner).state['taskpilot-alerts'],'true');await f.call('automation',{enabled:false});assert.equal(f.core.botContext(owner),null);});
test('Planning navigateur : une réponse ancienne ne remplace pas une modification déjà sauvegardée',async t=>{
 const originals={document:globalThis.document,window:globalThis.window,CustomEvent:globalThis.CustomEvent,location:globalThis.location};let revision=0,events=0,waiting=null;
 globalThis.document={querySelector:()=>null};globalThis.window={dispatchEvent:()=>events++};globalThis.location={hostname:'task-pilot.net'};globalThis.CustomEvent=class{constructor(type){this.type=type;}};
 t.mock.method(globalThis,'fetch',async(url,options)=>{if(options?.method==='PUT'){revision++;return {ok:true,json:async()=>({revision})};}if(waiting)return waiting;return {ok:true,json:async()=>({revision,state:{'taskpilot-alerts':'false'}})};});
 try{
  const {accountStorage}=await import('./account-storage.mjs?bot-sync-test');await accountStorage.initialize();
  accountStorage.setItem('taskpilot-alerts','true');assert.equal(await accountStorage.refresh(),false);await accountStorage.flush();
  let resolve;waiting=new Promise(r=>{resolve=r;});const refresh=accountStorage.refresh();
  accountStorage.setItem('taskpilot-alerts','false');await accountStorage.flush();const savedRevision=revision;
  resolve({ok:true,json:async()=>({revision:savedRevision-1,state:{'taskpilot-alerts':'true'}})});await refresh;
  assert.equal(accountStorage.getItem('taskpilot-alerts'),'false');assert.equal(events,0);
  waiting=null;revision++;assert.equal(await accountStorage.refresh(),true);assert.equal(events,1);
 }finally{for(const [key,value]of Object.entries(originals))if(value===undefined)delete globalThis[key];else globalThis[key]=value;}
});

test('Essai privé : identité serveur, dates, propriété et expiration',()=>{
 const now=Date.parse('2026-10-04T09:00:00Z'),config={id:'test-pilot',ownerEmail:'login@example.test',taskrabbitEmail:'rabbit@example.test',runDate:'2026-10-04',targetDate:'2026-10-05',expiresAt:'2026-10-04T16:00:00Z',maxRequests:1},raw=JSON.stringify(config),user={email:config.ownerEmail,taskrabbitEmail:config.taskrabbitEmail,emailVerified:true};
 assert.equal(privatePilot(raw,user,now).targetDate,'2026-10-05');
 for(const change of [{email:'other@example.test'},{taskrabbitEmail:'other@example.test'},{emailVerified:false}])assert.equal(privatePilot(raw,{...user,...change},now),null);
 assert.equal(privatePilot(raw,user,Date.parse(config.expiresAt)),null);assert.equal(privatePilot('invalid',user,now),null);assert.equal(privatePilot(JSON.stringify({...config,maxRequests:2}),user,now),null);
 assert.equal(parisDay(Date.parse('2026-10-03T22:30:00Z')),'2026-10-04');
 const pilot=privatePilot(raw,user,now);assert.equal(botSettings({...context,email:'memmoudkamel01@gmail.com',pilot},now).date,'2026-10-05');
 assert.throws(()=>botSettings({...context,pilot},now-86400000));assert.throws(()=>botSettings({...context,pilot:{...pilot,used:1}},now));
});
test('Essai privé : vérification obligatoire, une seule demande, pause et reprise ne réinitialisent rien',async()=>{
 const raw=JSON.stringify({id:'single',ownerEmail:'login@example.test',taskrabbitEmail:'memmoudkamel01@gmail.com',runDate:'2026-10-04',targetDate:'2026-10-05',expiresAt:'2026-10-04T16:00:00Z',maxRequests:1});
 const policy=u=>privatePilot(raw,u,Date.parse('2026-10-04T09:00:00Z'));
 const f=await accountFixture({approved:false,pilotFor:policy,taskrabbitEmail:'memmoudkamel01@gmail.com'});
 assert.equal((await f.call('automation',{enabled:true,acceptTerms:true})).status,400);
 await f.call('taskrabbit-verification');await f.core.waitForMail();await f.call('verify-taskrabbit',{token:f.sent.find(m=>m.purpose==='taskrabbit').token});
 assert.equal((await f.call('automation',{enabled:true,acceptTerms:false})).status,400);
 assert.equal((await f.call('automation',{enabled:true,acceptTerms:true})).status,200);
 const id=f.core.botUsers()[0].id;assert.equal(f.core.botContext(id).pilot.maxRequests,1);
 await f.core.botConsume(id);assert.equal(f.core.botUsers().length,0);assert.equal(f.core.botContext(id),null);assert.ok(f.core.botContext(id,true));
 await assert.rejects(f.core.botConsume(id));await f.call('automation',{enabled:false});assert.equal((await f.call('automation',{enabled:true,acceptTerms:true})).status,409);
 const restarted=await createAccountCore({storage:{load:async()=>f.database(),save:async()=>{}},pilotFor:policy});assert.equal(restarted.botUsers().length,0);assert.equal(restarted.botPolicy(id).pilot.used,1);
 const other=await accountFixture({approved:false,pilotFor:policy,taskrabbitEmail:'login@example.test'});assert.equal((await other.call('automation',{enabled:true,acceptTerms:true})).status,409);
});
