import {linePalette} from './line-palette.mjs';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=m=>Number.isFinite(m)?`${String(Math.floor(m/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`:'—';
const icons={walk:'<path d="m13 8-3 5 4 3-1 5m-3-8-4 3m6-7 4 3 3 1M10 13l-3 8"/><circle cx="14" cy="4" r="2"/>',rail:'<rect x="5" y="3" width="14" height="15" rx="4"/><path d="M5 10h14M9 21l2-3m4 3-2-3"/><circle cx="9" cy="14" r="1"/><circle cx="15" cy="14" r="1"/>',wait:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',transfer:'<path d="M4 8h15l-4-4M20 16H5l4 4"/>'};
function icon(kind){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[kind]||icons.rail}</svg>`;}
function kind(s){return s.type==='waiting'?'wait':s.type==='transfer'?'transfer':s.type==='public_transport'?'rail':'walk';}
function mode(s){const m=String(s.mode||'').toLowerCase();return m.includes('rer')?'RER':m.includes('metro')||m.includes('métro')?'Métro':m.includes('bus')?'Bus':m.includes('tram')?'Tram':s.mode||'Train';}
const hex=value=>/^#?[\da-f]{6}$/i.test(String(value||''))?'#'+String(value).replace(/^#/,'').toLowerCase():null;
function contrast(background){const rgb=background.slice(1).match(/../g).map(v=>{const c=parseInt(v,16)/255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4;});return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.179?'#000000':'#ffffff';}
export function lineColors(s,provider='idfm'){
 const m=mode(s),tone=m==='Métro'?'metro':m==='RER'?'rer':m==='Bus'?'bus':m==='Tram'?'tram':'train';
 const code=String(s.line||'').toUpperCase().replace(/^(?:MÉTRO|METRO|RER|LIGNE|TRAIN|TRANSILIEN)\s*/,'').replace(/\s/g,'').replace(/BIS$/,'B').replace(tone==='metro'?/^M(?=\d)/:/^$/,'');
 const fallback=provider==='idfm'?linePalette[tone+':'+code]:null;
 const background=hex(s.color)||fallback?.background||'#526579';
 const foreground=hex(s.textColor)||(!hex(s.color)?fallback?.foreground:null)||contrast(background);
 return {tone,background,foreground};
}
function badge(s,provider){const m=mode(s),line=s.line||'',colors=lineColors(s,provider);return `<span class="j-line ${colors.tone}" style="--line-bg:${colors.background};--line-fg:${colors.foreground}" aria-label="${escape(m+' '+line)}">${escape(line||m)}</span>`;}
export function journeyDetails(leg){if(!leg?.provider||leg.provider==='ign')return '';const steps=leg.steps||[];return `<details class="journey-card" open><summary><div class="j-heading"><div><span class="j-eyebrow">TRAJET ${leg.provider==='idfm'?'· ÎLE-DE-FRANCE':'· SNCF'}</span><strong>${time(leg.departure)} <span class="j-arrow">→</span> ${time(leg.arrival)}</strong></div><div class="j-total">${escape(leg.minutes)}<small>min</small></div></div><div class="j-preview">${steps.map(s=>kind(s)==='rail'?`<span class="j-preview-line">${badge(s,leg.provider)}</span>`:`<span class="j-preview-walk">${icon(kind(s))}<span>${escape(s.minutes||0)}′</span></span>`).join('<span class="j-chevron" aria-hidden="true">›</span>')}</div><div class="j-meta"><span>${icon('walk')}${escape(leg.walking)} min à pied</span><span>${leg.transfers?escape(leg.transfers)+' correspondance'+(leg.transfers>1?'s':''):'Direct'}</span><span class="j-toggle">Étapes <span aria-hidden="true">⌄</span></span></div></summary><ol class="j-steps">${steps.map(s=>{const k=kind(s);return `<li class="j-step ${k}"><div class="j-time">${time(s.departure)}</div><div class="j-track"><span class="j-node">${k==='rail'?badge(s,leg.provider):icon(k)}</span></div><div class="j-content">${k==='rail'?`<div class="j-step-title"><strong>${escape(s.from||'Monter à bord')}</strong><span>${escape(s.minutes)} min</span></div><div class="j-direction">${escape(mode(s))} ${escape(s.line)}${s.direction?' · Direction <b>'+escape(s.direction)+'</b>':''}</div><div class="j-destination"><span aria-hidden="true">↓</span><strong>${escape(s.to||'Arrivée')}</strong><time>${time(s.arrival)}</time></div>`:`<div class="j-step-title"><strong>${k==='wait'?'Attendre':k==='transfer'?'Correspondance':'Marcher'}</strong><span>${escape(s.minutes)} min</span></div><p class="j-walk-path">${escape(s.from)}${s.to?' → '+escape(s.to):''}</p>`}</div></li>`;}).join('')}</ol><div class="j-footer"><span class="j-live-dot ${leg.realtime?'live':''}"></span>${leg.realtime?'Données temps réel sur certaines étapes':'Horaires du calculateur · vérifier les perturbations'}${leg.warning?' · '+escape(leg.warning):''}</div></details>`;}
