import {test} from 'node:test';import assert from 'node:assert/strict';
import {defaults,optimize,normalizeTasks} from './model.mjs';import {mergeOffers,geocodeAddress} from './offers.mjs';import {routeKey,summarizeJourney} from './transit-core.mjs';
import {prepareRequests} from './request-queue.mjs';import {portalApi} from './portal-server.mjs';import {Readable} from 'node:stream';
import {roadJourney,roadSignature} from './road-routes.mjs';import {travel} from './model.mjs';
const date='2026-10-03',offer={id:'101',date,time:'10:00',duration:60,pay:100,lat:48.8566,lon:2.3522,address:'1 rue de Rivoli Paris',department:'Paris',brand:'IKEA',status:'available'};
test('Dates impossibles refusées',()=>assert.throws(()=>normalizeTasks([{...offer,date:'2026-02-31'}]),/invalide/));
test('Une durée ou un horaire modifié invalide le trajet entre missions',()=>{const q={...defaults,mobility:'transit'};assert.notEqual(routeKey(offer,offer,q,date,{arrivalBy:700}),routeKey({...offer,duration:120},offer,q,date,{arrivalBy:700}));});
test('Confirmation conservée même hors filtre de préférences',()=>{const p={...defaults,lat:offer.lat,lon:offer.lon,lunch:false,minPay:150,minRate:0,minDuration:100,brands:'Homary'};assert.equal(optimize(normalizeTasks([{...offer,status:'confirmed'}]),p,date).plans[0].seq[0].task.status,'confirmed');});
test('Fusion conserve coordonnées et demande en attente, sans doublon',()=>{const old={...offer,status:'pending',source:'portal'};const merged=mergeOffers([old],[{...offer,lat:null,lon:null,pay:120}]);assert.equal(merged.tasks.length,1);assert.equal(merged.tasks[0].status,'pending');assert.equal(merged.tasks[0].lat,offer.lat);assert.deepEqual(merged.changed,['101']);});
test('Changement d’adresse ne conserve pas les anciennes coordonnées',()=>assert.equal(mergeOffers([offer],[{...offer,address:'Autre adresse',lat:null,lon:null}]).tasks[0].lat,null));
test('Offre non visible signalée sans inventer une annulation',()=>{const result=mergeOffers([{...offer,status:'confirmed',source:'portal'}],[{...offer,id:'102'}],{complete:true});assert.equal(result.tasks[0].sourceMissing,true);assert.equal(result.tasks[0].status,'confirmed');});
test('Localisation IGN normalisée sans secret dans la requête',async()=>{const result=await geocodeAddress(offer.address,async url=>{assert.equal(url.origin,'https://data.geopf.fr');assert.equal(url.searchParams.get('q'),offer.address);return new Response(JSON.stringify({features:[{geometry:{coordinates:[2.35,48.85]},properties:{label:'1 Rue de Rivoli',score:.92,type:'housenumber'}}]}));});assert.equal(result[0].lat,48.85);assert.equal(result[0].type,'housenumber');});
test('Les secondes des étapes ne créent pas un chevauchement affiché',()=>{const j=summarizeJourney({departure_date_time:'20261003T090000',arrival_date_time:'20261003T091100',sections:[{departure_date_time:'20261003T090000',arrival_date_time:'20261003T090130'},{departure_date_time:'20261003T090130',arrival_date_time:'20261003T091100'}]},date,'idfm');assert.equal(j.steps[0].arrival,j.steps[1].departure);});
test('Une pause peut occuper l’attente avant la mission',()=>{const p={...defaults,mobility:'transit',lat:offer.lat,lon:offer.lon,lunch:true,lunchStart:'12:00',lunchDuration:45,minRate:0,minPay:0,returnHome:false},t={...offer,time:'13:00'},home={id:'home',lat:p.lat,lon:p.lon},matrix={[routeKey(home,t,p,date,{arrivalBy:770})]:{available:true,departure:660,arrival:700,minutes:40,km:1,fetchedAt:Date.now()}};assert.equal(optimize(normalizeTasks([t]),p,date,matrix).plans.length,1);});
test('Préparation idempotente et exclusion des demandes déjà en cours',()=>{const first=prepareRequests({},[offer,{...offer,id:'102',status:'pending'}]);const second=prepareRequests(first,[offer]);assert.equal(Object.keys(second).length,1);assert.equal(second['101'].preparedAt,first['101'].preparedAt);assert.equal(second['101'].state,'prepared');});
test('Route IGN : secondes converties en minutes, sans promesse de trafic réel',async()=>{const r=await roadJourney(offer,offer,'car',async url=>{assert.equal(url.searchParams.get('timeUnit'),'second');assert.equal(url.searchParams.get('profile'),'car');return new Response(JSON.stringify({duration:482.8,distance:2.48}));});assert.equal(r.minutes,9);assert.equal(r.estimated,true);});
test('Route calculée invalidée quand les coordonnées changent',()=>{const a={...offer,id:'home'},b={...offer,id:'101'},matrix={'home>101':{available:true,minutes:99,km:1,mode:'car',provider:'ign',signature:roadSignature(a,b,'car'),fetchedAt:Date.now()}};assert.equal(travel(a,b,defaults,matrix).minutes,99);assert.notEqual(travel({...a,lat:a.lat+.01},b,defaults,matrix).minutes,99);});
test('Compagnon : association locale, jeton obligatoire, capture valide',async()=>{async function call(path,body,headers={}){const req=Readable.from([Buffer.from(JSON.stringify(body))]);req.method='POST';req.headers={host:'127.0.0.1:4173','content-type':'application/json',...headers};let status,result;await portalApi(req,{writeHead(code){status=code;},end(value){result=JSON.parse(value);}},new URL(path,'http://127.0.0.1:4173'));return {status,result};}assert.equal((await call('/api/portal/pair',{}, {origin:'https://example.com'})).status,403);const {result}=await call('/api/portal/pair',{}, {origin:'http://127.0.0.1:4173'});assert.equal((await call('/api/portal/snapshot',{source:'taskrabbit-board',tasks:[offer]})).status,403);assert.equal((await call('/api/portal/snapshot',{source:'taskrabbit-board',tasks:[offer]},{'x-taskpilot-token':result.token})).status,200);});

test('Import manuel conserve les réservations entrantes sans fabriquer une confirmation depuis la liste du portail',()=>{const incoming={...offer,status:'pending'};assert.equal(mergeOffers([],[incoming],{preserveIncomingStatus:true}).tasks[0].status,'pending');assert.equal(mergeOffers([],[incoming]).tasks[0].status,'available');});

test('Les captures du compagnon ne sont visibles que par le compte associé',async()=>{async function call(owner,route,method='GET',body={},token=''){const req=Readable.from([Buffer.from(JSON.stringify(body))]);req.method=method;req.headers={host:'127.0.0.1:4173',origin:'http://127.0.0.1:4173','content-type':'application/json','x-taskpilot-token':token};let result;await portalApi(req,{writeHead(){},end(value){result=JSON.parse(value);}},new URL(route,'http://127.0.0.1:4173'),owner);return result;}const pair=await call('owner-a','/api/portal/pair','POST');await call('owner-a','/api/portal/snapshot','POST',{source:'taskrabbit-board',tasks:[offer]},pair.token);assert.equal((await call('owner-b','/api/portal/snapshot')).snapshot,null);assert.equal((await call('owner-a','/api/portal/snapshot')).snapshot.tasks.length,1);});
