import {accountStorage} from './account-storage.mjs';
import {geocodeAddress} from './offers.mjs';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function setupOffers({getTasks,setTasks,onSnapshot}){let watching=false,revision=0,timer,busy=false;const status=document.querySelector('#offerStatus');const pending=new Map();let alerts=accountStorage.getItem('taskpilot-alerts')==='true';document.querySelector('#enableOfferAlerts').onclick=async()=>{if(!('Notification' in window)){status.textContent='Les alertes navigateur ne sont pas disponibles ici. Les alertes dans l’app restent actives.';return;}const permission=await Notification.requestPermission();alerts=permission==='granted';accountStorage.setItem('taskpilot-alerts',String(alerts));status.textContent=alerts?'Alertes activées pendant que TaskPilot est ouvert.':'Permission non accordée : les alertes restent visibles dans l’app.';};
 const render=()=>{document.querySelector('#geoReview').innerHTML=[...pending].map(([id,results])=>`<article class="task-card"><div class="body"><strong>${escape(getTasks().find(t=>t.id===id)?.address||id)}</strong><p>Choisissez une adresse précise ; un centre de commune ne suffit pas.</p>${results.map((r,i)=>`<button class="secondary" data-geocode="${escape(id)}" data-option="${i}">${escape(r.label)} · ${Math.round(r.score*100)} %</button>`).join('')||'<p>Aucun résultat fiable : complétez la mission manuellement.</p>'}</div></article>`).join('');document.querySelectorAll('[data-geocode]').forEach(b=>b.onclick=()=>{const r=pending.get(b.dataset.geocode)[Number(b.dataset.option)];setTasks(getTasks().map(t=>t.id===b.dataset.geocode?{...t,lat:r.lat,lon:r.lon,geocode:{label:r.label,score:r.score,type:r.type,verified:true}}:t));pending.delete(b.dataset.geocode);render();});};
 document.querySelector('#geocodeAll').onclick=async()=>{if(busy)return;busy=true;const button=document.querySelector('#geocodeAll');button.disabled=true;const missing=getTasks().filter(t=>t.lat==null||t.lon==null);let done=0;try{for(const t of missing){status.textContent=`Recherche IGN : ${++done} / ${missing.length}`;const results=await geocodeAddress(t.address);const r=results[0];if(r&&r.type==='housenumber'&&r.score>=.85&&(!results[1]||r.score-results[1].score>.1))setTasks(getTasks().map(task=>task.id===t.id?{...task,lat:r.lat,lon:r.lon,geocode:{...r,verified:false}}:task));else pending.set(t.id,results);render();await new Promise(r=>setTimeout(r,250));}status.textContent=pending.size?`${pending.size} adresse(s) à vérifier ci-dessous.`:'Adresses localisées. Recalculez les trajets.';}catch(e){status.textContent=e.message;}finally{busy=false;button.disabled=false;}};
 document.querySelector('#pairPortal').onclick=async()=>{try{const r=await fetch('/api/portal/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Impossible de créer le code : redémarrez le serveur local.');document.querySelector('#pairCode').value=(await r.json()).token;document.querySelector('#pairDialog').showModal();}catch(e){status.textContent=e.message;}};
 document.querySelector('#copyPair').onclick=()=>navigator.clipboard.writeText(document.querySelector('#pairCode').value).then(()=>status.textContent='Code copié. Collez-le dans le compagnon.');
 async function poll(){if(!watching)return;try{const r=await fetch('/api/portal/snapshot?after='+revision);if(!r.ok)throw Error('Le connecteur local ne répond plus.');const data=await r.json();if(data.snapshot){revision=data.revision;const previous=new Set(getTasks().map(t=>t.id));onSnapshot(data.snapshot);const count=data.snapshot.tasks.filter(t=>!previous.has(t.id)).length;if(count&&alerts&&'Notification' in window&&Notification.permission==='granted')new Notification('TaskPilot',{body:count+' nouvelle(s) offre(s) reçue(s). Vérifiez le planning.'});status.textContent='Dernière liste reçue : '+new Date(data.snapshot.seenAt).toLocaleTimeString('fr-FR')+' · '+data.snapshot.tasks.length+' offres visibles.';}else{const info=await (await fetch('/api/portal/status')).json();status.textContent=info.lastSeenAt?'Dernière lecture : '+new Date(info.lastSeenAt).toLocaleTimeString('fr-FR')+(Date.now()-info.lastSeenAt>180000?' · Liste ancienne : vérifiez le portail.':''):'En attente du compagnon. Ouvrez le portail et activez sa surveillance.';}}catch(e){status.textContent=e.message;}finally{if(watching)timer=setTimeout(poll,5000);}}
 document.querySelector('#toggleWatch').onclick=()=>{watching=!watching;document.querySelector('#toggleWatch').textContent=watching?'Arrêter le suivi des offres':'Activer le suivi des offres';clearTimeout(timer);if(watching)poll();else status.textContent='Suivi arrêté.';};
}
