import {test} from 'node:test';import assert from 'node:assert/strict';import {defaults,optimize,normalizeTasks,demo,parseBlocked,validatePrefs,tomorrow} from './model.mjs';
import {zoneReason,departmentCode,geographicDistance} from './zone-model.mjs';
const date='2026-10-03',base={...defaults,lunch:false,overrun:0,gap:20,maxPending:12,minRate:0,minPay:0,maxKm:500,returnHome:false};
function task(id,time,duration=60,pay=50,extra={}){return normalizeTasks([{id,date,time,duration,pay,lat:base.lat,lon:base.lon,...extra}])[0];}
test('Exclut les chevauchements et respecte la marge hors trajet',()=>{const ts=[task('a','09:00'),task('b','10:10'),task('c','10:30')];const {plans}=optimize(ts,base,date);assert.deepEqual(plans[0].seq.map(x=>x.task.id),['a','c']);});
test('Inclut le trajet entre missions dans la faisabilité',()=>{const ts=[task('a','09:00'),task('b','10:30')];const {plans}=optimize(ts,base,date,{'a>b':{minutes:40,km:10}});assert.equal(plans[0].seq.length,1);});
test('La pause bloque aussi les déplacements',()=>{const ts=[task('a','13:30')];const p={...base,lunch:true,lunchStart:'12:30',lunchDuration:45};assert.equal(optimize(ts,p,date,{'home>a':{minutes:40,km:10}}).plans.length,0);});
test('Retour trop tardif exclu',()=>{assert.equal(optimize([task('a','18:00')],{...base,returnHome:true,end:'19:00'},date,{'a>home':{minutes:30,km:5}}).plans.length,0);});
test('Obligations en attente maintenues et conflit signalé',()=>{const ts=[task('a','09:00',60,50,{status:'pending'}),task('b','09:30',60,150)];assert.deepEqual(optimize(ts,base,date).plans[0].seq.map(x=>x.task.id),['a']);assert.equal(optimize([task('a','09:00',60,50,{status:'pending'}),task('b','09:30',60,50,{status:'confirmed'})],base,date).fixedConflict,true);});
test('Plafond inclut demandes existantes et propositions',()=>{const ts=[task('a','09:00',60,50,{status:'pending'}),task('b','11:00')];assert.equal(optimize(ts,{...base,maxPending:1},date).plans[0].seq.length,1);});
test('Pas de trajet inventé quand coordonnées absentes',()=>{assert.equal(optimize([task('a','09:00',60,50,{lat:null,lon:null})],base,date).plans.length,0);});
test('Revenu net, frais et attente calculés sur la journée mobilisée',()=>{const p={...base,objective:'income',gap:0};const plan=optimize([task('a','09:00'),task('b','12:00')],p,date).plans[0];assert.equal(plan.occupied,240);assert.equal(plan.rate,25);});
test('Invalides refusés, doublons et créneaux invalides',()=>{assert.throws(()=>normalizeTasks([task('a','09:00'),task('a','10:00')]));assert.throws(()=>parseBlocked('11:00-10:00'));assert.throws(()=>validatePrefs({...base,speed:0}));});
test('Démo fournit un planning et toutes les contraintes sont respectées',()=>{const {plans}=optimize(demo(date),defaults,date);assert.ok(plans.length);for(const s of plans){assert.ok(s.end<=19*60);for(let i=1;i<s.seq.length;i++)assert.ok(s.seq[i].depart>=s.seq[i-1].finish+defaults.gap);}});
test('Une mission tardive rentable ne compte pas le matin libre comme travail',()=>{assert.ok(optimize([task('a','16:00',60,60)],{...base,minRate:50},date).plans.length);});
test('Un retour intermédiaire impossible ne supprime pas une séquence finissant ailleurs',()=>{const ts=[task('a','09:00'),task('b','11:00')];const matrix={'a>home':{minutes:700,km:600},'a>b':{minutes:10,km:5},'b>home':{minutes:10,km:5}};const plans=optimize(ts,{...base,returnHome:true},date,matrix).plans;assert.equal(plans[0].seq.length,2);});
test('Sélection multiple de départements : code, nom et accents',()=>{const p={...base,zoneMode:'departments',departments:'Rhône,Ain'};assert.equal(zoneReason(task('a','09:00',60,50,{department:'Rhone'}),p),null);assert.equal(zoneReason(task('b','09:00',60,50,{department:'01'}),p),null);assert.equal(zoneReason(task('c','09:00',60,50,{department:'Paris'}),p),'Département non sélectionné');});
test('Sans département sélectionné, aucune mission retenue',()=>assert.equal(zoneReason(task('a','09:00'),{...base,zoneMode:'departments',departments:''}),'Aucun département sélectionné'));
test('Rayon : même distance géographique pour la carte et le filtre',()=>{const p={...base,zoneMode:'radius',radiusKm:20};assert.equal(zoneReason(task('a','09:00'),p),null);const distant=task('b','09:00',60,50,{lat:48.8566,lon:2.3522});assert.ok(geographicDistance(p,distant)>20);assert.equal(zoneReason(distant,p),'Hors du rayon choisi');assert.equal(optimize([distant],p,date).plans.length,0);});
test('Les exclusions restent prioritaires dans tous les modes',()=>assert.equal(zoneReason(task('a','09:00',60,50,{department:'69'}),{...base,zoneMode:'all',excluded:'Rhône'}),'Département exclu'));
test('Reconnaît le département du portail Montpellier et un code postal',()=>{assert.equal(departmentCode({department:'Montpellier'}),'34');assert.equal(departmentCode({department:'',address:'Commune 75011'}),'75');});
test('Rayon invalide refusé',()=>assert.throws(()=>validatePrefs({...base,radiusKm:0})));

test('Un nom de lieu non vérifié ne produit pas de planning',()=>{assert.throws(()=>optimize(demo(tomorrow()),{...defaults,origin:'Paris',placeResolved:false},tomorrow()),/Sélectionnez votre point de départ/);});
test('Paris avec un rayon de 50 km exclut la démonstration lyonnaise',()=>{const date=tomorrow(),p={...defaults,origin:'Paris',lat:48.8566,lon:2.3522,placeResolved:true,zoneMode:'radius',radiusKm:50};const result=optimize(demo(date),p,date);assert.equal(result.eligible,0);assert.equal(result.plans.length,0);});
