import {isWorkingDate} from './workdays.mjs';
import {loadCredentials,saveCredentials} from './credential-store.mjs';
import {randomUUID} from 'node:crypto';
import {defaults,validatePrefs,normalizeTasks,reasons,mins} from './model.mjs';
import {routeKey} from './transit-core.mjs';
import {queryTransit} from './transit-provider.mjs';
const stored=await loadCredentials();let protectedStorage=!!(stored.idfm||stored.sncf);const credentials={idfm:process.env.PRIM_API_KEY||stored.idfm||'',sncf:process.env.SNCF_API_KEY||stored.sncf||''},jobs=new Map(),cache=new Map();
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function body(req){const chunks=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>500000)throw fail('Requête trop volumineuse.',413);chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw fail('JSON invalide.');}}
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));}
async function runJob(job,tasks,p,date,token){const home={id:'home',lat:p.lat,lon:p.lon};const edges=[];const finish=t=>mins(t.time)+Math.ceil(t.duration*(1+p.overrun/100));for(const target of tasks){const arrivalBy=mins(target.time)-p.transitBuffer;edges.push({from:home,to:target,arrivalBy,ready:mins(p.start),maxMinutes:p.maxFirst});for(const source of tasks)if(source.id!==target.id&&finish(source)+p.gap<=arrivalBy)edges.push({from:source,to:target,arrivalBy,ready:finish(source)+p.gap,maxMinutes:p.maxTravel});}if(p.returnHome)for(const source of tasks)edges.push({from:source,to:home,departureAt:finish(source),ready:finish(source),maxMinutes:p.maxTravel});job.total=edges.length;const matrix={};try{for(const edge of edges){if(job.controller.signal.aborted)throw fail('Calcul arrêté.');const key=routeKey(edge.from,edge.to,p,date,edge);const cached=cache.get(key);let leg;if(cached&&Date.now()-cached.fetchedAt<600000){leg=cached;job.cached++;}else{const signal=AbortSignal.any([job.controller.signal,AbortSignal.timeout(20000)]);leg=await queryTransit({...edge,p,date,token,signal});leg.fetchedAt=Date.now();for(const [cacheKey,value]of cache)if(Date.now()-value.fetchedAt>=600000)cache.delete(cacheKey);if(cache.size>=10000)cache.delete(cache.keys().next().value);cache.set(key,leg);await pause(500);}matrix[key]=leg;if(!leg.available)job.unavailable++;job.completed++;}job.state='done';job.result={matrix,unavailable:job.unavailable,missionCount:tasks.length,completed:job.completed};}catch(e){job.state=job.controller.signal.aborted?'cancelled':'error';job.error=e.name==='TimeoutError'?'Le fournisseur n’a pas répondu à temps.':e.message||'Le calcul a échoué.';}finally{job.controller=undefined;job.finishedAt=Date.now();}}
export async function transitApi(req,res,url,ownerId='test'){try{
 if(!['127.0.0.1:4173','localhost:4173'].includes(req.headers.host))throw fail('Hôte non autorisé.',403);
 if(req.method==='POST'&&(!['http://127.0.0.1:4173','http://localhost:4173'].includes(req.headers.origin)||!req.headers['content-type']?.startsWith('application/json')))throw fail('Requête non autorisée.',403);
 if(url.pathname==='/api/transit/status'&&req.method==='GET')return json(res,200,{idfm:!!credentials.idfm,sncf:!!credentials.sncf,protectedStorage});
 if(url.pathname==='/api/transit/credentials'&&req.method==='POST'){const data=await body(req);if(!['idfm','sncf'].includes(data.provider)||typeof data.token!=='string'||data.token.length>300||/[\r\n]/.test(data.token))throw fail('Clé ou fournisseur invalide.');credentials[data.provider]=data.token;try{protectedStorage=await saveCredentials(credentials);}catch{protectedStorage=false;}cache.clear();return json(res,200,{configured:!!data.token});}
 if(url.pathname==='/api/transit/jobs'&&req.method==='POST'){const data=await body(req),p={...defaults,...data.p};validatePrefs(p);if(p.mobility!=='transit')throw fail('Sélectionnez les transports en commun.');if(!/^\d{4}-\d{2}-\d{2}$/.test(data.date||'')||!Number.isFinite(Date.parse(data.date))||new Date(data.date).toISOString().slice(0,10)!==data.date)throw fail('Date invalide.');if(!isWorkingDate(data.date,p))throw fail('Jour de repos : la planification est désactivée pour cette date.',409);if(!credentials[p.transitProvider])throw fail('Configurez d’abord la clé API du fournisseur choisi.',409);if([...jobs.values()].some(j=>j.state==='running'))throw fail('Un calcul est déjà en cours. Attendez sa fin ou arrêtez-le.',409);const tasks=normalizeTasks(data.tasks).filter(t=>!reasons(t,p,data.date).length);if(!tasks.length)throw fail('Aucune mission ne respecte les critères.');if(tasks.length>20)throw fail('Limitez la zone ou les filtres à 20 missions pour calculer les horaires.');const job={ownerId,id:randomUUID(),state:'running',completed:0,total:0,cached:0,unavailable:0,controller:new AbortController(),createdAt:Date.now()};for(const [id,j]of jobs)if(Date.now()-j.createdAt>3600000)jobs.delete(id);jobs.set(job.id,job);void runJob(job,tasks,p,data.date,credentials[p.transitProvider]);return json(res,202,{id:job.id});}
 const match=url.pathname.match(/^\/api\/transit\/jobs\/([a-f0-9-]+)(\/cancel)?$/);if(match){const job=jobs.get(match[1]);if(!job||job.ownerId!==ownerId)throw fail('Calcul introuvable.',404);if(match[2]&&req.method==='POST'){job.controller?.abort();return json(res,200,{cancelled:true});}if(!match[2]&&req.method==='GET'){const {controller,...status}=job;return json(res,200,status);}}
 throw fail('API introuvable.',404);
 }catch(e){json(res,e.status||500,{error:e.status?e.message:'Erreur du serveur local.'});}}
