import {transportNames} from './transit-core.mjs';
export class TransportSettings{
 constructor(root,p,{onCalculate,onStatus}){this.root=root;this.root.innerHTML=`<div class="transport-head"><h3>Comment vous déplacez-vous ?</h3><p class="muted">Le mode choisi détermine les trajets et les frais utilisés dans votre planning.</p></div><div class="transport-modes" role="group" aria-label="Mode de déplacement">${Object.entries(transportNames).map(([m,name])=>`<button type="button" data-mobility="${m}" aria-pressed="${p.mobility===m}"><span>${({car:'🚗',bike:'🚲',walk:'🚶',transit:'🚆'})[m]}</span>${name}</button>`).join('')}</div><div id="mobilityDetails"></div>`;this.value={mobility:p.mobility||'car',transitProvider:p.transitProvider||'idfm',maxTransfers:p.maxTransfers??2,maxWalk:p.maxWalk??20,transitBuffer:p.transitBuffer??10,walkSpeed:p.walkSpeed??5,bikeSpeed:p.bikeSpeed??15,transitSubscription:p.transitSubscription??true,transitDailyCost:p.transitDailyCost??0,transitFarePerLeg:p.transitFarePerLeg??3};this.onCalculate=onCalculate;this.onStatus=onStatus;this.root.querySelectorAll('[data-mobility]').forEach(b=>b.onclick=()=>{this.read();this.value.mobility=b.dataset.mobility;this.draw();this.root.dispatchEvent(new Event("criteriachange",{bubbles:true}));});this.draw();}
 number(name,label,min,max,step=1){return `<label>${label}<input data-transport="${name}" type="number" min="${min}" max="${max}" step="${step}" value="${this.value[name]}" required></label>`;}
 read(){this.root.querySelectorAll('[data-transport]').forEach(i=>{this.value[i.dataset.transport]=i.type==='checkbox'?i.checked:i.type==='number'?Number(i.value):i.value;});return {...this.value};}
 getValue(){return this.read();}
 draw(){const v=this.value;this.root.querySelectorAll('[data-mobility]').forEach(b=>{b.classList.toggle('selected',b.dataset.mobility===v.mobility);b.setAttribute('aria-pressed',b.dataset.mobility===v.mobility);});const details=this.root.querySelector('#mobilityDetails');details.innerHTML=v.mobility==='transit'?`<div class="field-grid"><label>Réseau / calculateur<select data-transport="transitProvider"><option value="idfm" ${v.transitProvider==='idfm'?'selected':''}>Île-de-France · RATP, RER, Transilien…</option><option value="sncf" ${v.transitProvider==='sncf'?'selected':''}>Train SNCF · hors réseau urbain</option></select></label>${this.number('maxTransfers','Correspondances maximum',0,8)}${this.number('maxWalk','Marche totale maximum par trajet (min)',0,120)}${this.number('transitBuffer','Arriver avant la mission (min)',0,120)}${this.number('walkSpeed','Vitesse de marche (km/h)',1,8,.5)}<label class="checkbox"><input type="checkbox" data-transport="transitSubscription" ${v.transitSubscription?'checked':''}>J’ai un abonnement couvrant ces trajets</label>${this.number('transitDailyCost','Coût journalier de l’abonnement (€)',0,200,.1)}${this.number('transitFarePerLeg','Budget par trajet sans abonnement (€)',0,500,.1)}</div><p class="muted">Le calcul inclut la marche d’accès, les correspondances et les horaires à la date choisie. Les coûts sont vos estimations, sans achat de billet ni vérification de couverture de l’abonnement.</p><div class="api-connection"><h4>Horaires inclus avec TaskPilot</h4><p id="apiStatus" role="status">Vérification de la configuration…</p><p class="muted">Le bouton de calcul utilise le fournisseur choisi pour les positions et horaires de vos missions.</p><button type="button" class="primary" id="calculateTransit">Enregistrer et calculer les horaires</button><button type="button" class="secondary" id="cancelTransit" hidden>Arrêter le calcul</button><p id="transitProgress" role="status" aria-live="polite"></p><small>20 missions maximum par calcul. Les trajets sont mis en cache pendant 10 minutes. Les horaires ne garantissent pas l’absence de perturbations.</small></div>`:v.mobility==='bike'?`<div class="field-grid">${this.number('bikeSpeed','Vitesse moyenne à vélo (km/h)',3,40,.5)}</div><p class="muted">Trajets estimés à partir de la distance et du détour. Les aménagements cyclables et le relief ne sont pas pris en compte. Les frais kilométriques restent réglables dans Revenus.</p>`:v.mobility==='walk'?`<div class="field-grid">${this.number('walkSpeed','Vitesse de marche (km/h)',1,8,.5)}</div><p class="muted">Trajets estimés à pied. Aucun coût kilométrique n’est déduit.</p>`:'<p class="muted">Les trajets en voiture utilisent votre vitesse moyenne et le coefficient de détour ci-dessous. Les temps de trajet renseignés manuellement sont prioritaires.</p>';
 this.onStatus?.(v.mobility);if(v.mobility!=='transit')return;const provider=this.root.querySelector('[data-transport="transitProvider"]');provider.onchange=()=>{this.read();this.refreshStatus();};this.root.querySelector('#calculateTransit').onclick=()=>this.onCalculate(this);this.refreshStatus();}
 async refreshStatus(){const el=this.root.querySelector('#apiStatus');if(!el)return;const provider=this.read().transitProvider;try{const response=await fetch('/api/transit/status');if(!response.ok)throw Error();const data=await response.json();if(this.read().transitProvider!==provider)return;el.textContent=data[provider]?'Horaires prêts · inclus avec TaskPilot':'Horaires temporairement indisponibles. La configuration est gérée par TaskPilot.';}catch{el.textContent='Impossible de vérifier les horaires. Réessayez dans quelques instants.';}}
}
